### ISSUE TITLE
shadowsocks-libev for openwrt does not run on boot if configured with "-b 127.0.0.1"

### ISSUE THREAD

**Issue by cattyhouse** [shadowsocks/openwrt-shadowsocks#100]
* If I change `/etc/init.d/shadowsock` from this:
```` bash
start() {
        service_start /usr/bin/ss-local -c $CONFIG -b 0.0.0.0
}
````
to:

```` bash
start() {
        service_start /usr/bin/ss-local -c $CONFIG -b 127.0.0.1
}
````
shadowsocks-libev does not run **on boot**, and yes, i have added it run level `/etc/init.d/shadowsocks enable`

* but if i run it after boot like this  `/etc/init.d/shadowsocks restart`, it works without any problem. 

* shadowsocks version, `ss-local -v | grep shadowsocks-libev`
> shadowsocks-libev 2.2.2

* Openwrt version, `cat /etc/openwrt_version`
> 14.07

* I also tried to keep `/etc/init.d/shadowsocks` unchanged, but configure `/etc/shadowsocks.json` with `"local":"127.0.0.1",` shadowsocks-libev still does not run **on boot**.  
* Also if i stop the service and then run `ss-local -c /etc/shadowsocks.json -b 127.0.0.1` , it works without out any problem.

**Comment by aa65535** [comment]
You can add a `sleep 5` in the init file.

BTW: Use `local_address` rather than `local` in the shadowsocks.json file.
