### ISSUE TITLE
missing -spec* option in the latest openwrt git version

### ISSUE THREAD

**Issue by lightingland** [shadowsocks/openwrt-shadowsocks#102]
I use the same command to get the latest shadowsocks,
git clone https://github.com/shadowsocks/openwrt-shadowsocks.git package/shadowsocks-libev

Turns out there are only -libev and -libev-polarssl show up in the menuconfig. The -spec* two options I needed are missing for openwrt.

**Comment by aa65535** [comment]
https://github.com/openwrt/packages/pull/1530
