### ISSUE TITLE
请问个技术问题

### ISSUE THREAD

**Issue by keivenliao** [shadowsocks/openwrt-shadowsocks#104]
http://wiki.openwrt.org/toh/linksys/ea4500
我的EA4500 是 Marvell Feroceon 88F6282 @1200Mhz CPU ，要如何才能编译对应的 Shadowsocks 和 Chinadns 呢？

**Comment by aa65535** [comment]
使用这里的 SDK https://downloads.openwrt.org/snapshots/trunk/kirkwood/generic/

**Comment by keivenliao** [comment]
我有个Ubuntu 环境，能否详细说明一下，我该怎么做吗？
