### ISSUE TITLE
 openwrt-dist website under maintenance?

### ISSUE THREAD

**Issue by scenix007** [shadowsocks/openwrt-shadowsocks#108]
cannot access http://openwrt-dist.sourceforge.net/
cannot update package through opkg upgrade.

**Comment by Crystommy** [comment]
https://github.com/shadowsocks/openwrt-shadowsocks/releases

**Comment by scenix007** [comment]
so, from now on, I can say goodbye to opkg update?

**Comment by aa65535** [comment]
http://sourceforge.net/blog/

I also hope this is only temporary.

**Comment by scenix007** [comment]
No latest version 2.2.3 on openwrt-dist.sourceforge.net, can you see to that?

**Comment by cokebar** [comment]
online again. @aa65535 will you continue to upload pre-compiled files to sourceforge?
