### ISSUE TITLE
在 Centos (vps of DO) 下无法make menuconfig

### ISSUE THREAD

**Issue by searich** [shadowsocks/openwrt-shadowsocks#110]
这是make -j1 V=s menuconfig 的输出，
[root@xxx OpenWrt-SDK-15.05-rc3-arm64_gcc-4.8-linaro_glibc-2.19.Linux-x86_64]# make -j1 V=s menuconfig
make[1]: Entering directory `/tmp/OpenWrt-SDK-15.05-rc3-arm64_gcc-4.8-linaro_glibc-2.19.Linux-x86_64/scripts/config'
In file included from mconf.c:23:
lxdialog/dialog.h:38:20: error: curses.h: No such file or directory
In file included from mconf.c:23:
lxdialog/dialog.h:103: error: expected specifier-qualifier-list before 'chtype'
lxdialog/dialog.h:200: error: expected ')' before '*' token
lxdialog/dialog.h:221: error: expected ')' before '*' token
lxdialog/dialog.h:223: error: expected ')' before '*' token
lxdialog/dialog.h:224: error: expected ')' before '*' token
lxdialog/dialog.h:225: error: expected ')' before '*' token
lxdialog/dialog.h:226: error: expected ')' before '*' token
lxdialog/dialog.h:228: error: expected ')' before '*' token
mconf.c: In function 'conf':
mconf.c:666: error: 'KEY_MAX' undeclared (first use in this function)
mconf.c:666: error: (Each undeclared identifier is reported only once
mconf.c:666: error: for each function it appears in.)
mconf.c: In function 'show_help':
mconf.c:786: error: 'stdscr' undeclared (first use in this function)
mconf.c: In function 'conf_choice':
mconf.c:858: error: 'KEY_MAX' undeclared (first use in this function)
make[1]: *** [mconf.o] Error 1
make[1]: Leaving directory `/tmp/OpenWrt-SDK-15.05-rc3-arm64_gcc-4.8-linaro_glibc-2.19.Linux-x86_64/scripts/config'
make: *** [scripts/config/mconf] Error 2

**Comment by aa65535** [comment]
OpenWrt 建议使用 Ubuntu 或者 Debian
