### ISSUE TITLE
OneDrive 上传失败（RST）

### ISSUE THREAD

**Issue by liukangxu** [shadowsocks/openwrt-shadowsocks#111]
开启 ShadowSocks 全局代理或忽略模式时，OneDrive 无法正常上传（TCP RST），添加以下两条排除规则后正常：
134.170.108.0/24    // OneDrive 客户端上传 IP 段
65.55.0.0/16    // 网页版 OneDrive 取回其他 PC 文件 IP 段

**Comment by cokebar** [comment]
@liukangxu 上传了一个300MB+的文件 无法重现你的问题
最好有ss的日志

**Comment by aa65535** [comment]
个例，无法重现
