### ISSUE TITLE
shadowsocks-libev-spec kills the server 

### ISSUE THREAD

**Issue by mveplus** [shadowsocks/openwrt-shadowsocks#112]
Each time I start the router(DIR-505) and my router connects to the VPS shadowsocks server ( ver.2.6.11), instance on the server dies. I have to start it again. The same time if I turn off the router,  shadowsocks works just fine on Windows 7 PC and Mac OS X Mavericks for a few days. The moment I start the router it kills the server.
Setup is on DIR-505 with OpenWRT Barrier Breaker and shadowsocks-libev-spec_2.2.2-1_ar71xx.ipk & luci-app-shadowsocks-spec_1.3.2-1_all.ipk. I did setup the router and installed the packages manually (scp) it pulled up all dependencies . I used luci config. Proxy setting is: Ignore List, TCP+UDP

My setup: 
ISP<>Firber-optic-Network-converter<>Main Router-WiFi <> WiFi client (DIR-505)<>Mac-conencted-to-Ethernet-port( DIR-505).

I just started "ssserver" with log and verbose mode now and I did killed the server today three times, but when I tried just now I cloud not replicate it... but I notice that "ss-redir" on the router (DIR-505) creates easily 100+ connections to the server...  and not only one PC is connected to the router.

Any advice?

Best regards,

**Comment by aa65535** [comment]
Try to use the new version.
