### ISSUE TITLE
shadowsocks-libev-spec 2.2.3通过luci配置自定义UDP转发使用不同IP会无法生效。

### ISSUE THREAD

**Issue by adolink** [shadowsocks/openwrt-shadowsocks#115]
如果只是启用，使用同一服务器配置功能正常，可在在PC客户机通过nslookup www.youtube.com 8.8.8.8获得与VPS上相同的正确IP，PS4的nat状态也是2。
如果使用自定义upd转发，使用不同的服务器IP，客户机nslookup 8.8.8.8返回的全是虚假IP。PS4的nat状态错误。
另外：使用同一服务器IP虽然客户机是正确的转发了udp，但是路由本身貌似并没有。返回仍旧是虚假ip，所以不得不继续使用 ss-tunnel来作为chinaDNS的上端，而不能直接使用8.8.8.8。

**Comment by cokebar** [comment]
UDP-relay 无法代理路由器自己的UDP流量 所以还是要用ss-tunnel
还有 LZ说的几处UDP转发应该指的UDP中继（relay）吧

**Comment by aa65535** [comment]
无法重现，请保证你的自定义服务器是可用的。
建议自定义服务器与全局设置中的服务器应该在地域上相近。
UDP relay 是无法应用到自身的。
