### ISSUE TITLE
采用方案5之后,Sketch和Sketch Mirror无法连接

### ISSUE THREAD

**Issue by zyallday** [shadowsocks/openwrt-shadowsocks#116]
采用的是[方案5](http://sourceforge.net/p/openwrt-dist/wiki/Plan5/)配置的,翻墙共享没有问题,但是最近发现办公室内的设计师需要用[Sketch](https://itunes.apple.com/cn/app/sketch-3/id852320343?mt=12) 和 [Sketch Mirror](https://itunes.apple.com/cn/app/sketch-mirror/id677296955?mt=8)在内网环境下同步设计稿来看,在 Mac的Sketch可以看到内网的iOS设备,但是无法连接成功,关闭ChinaDNS和Shadowsocks之后可以连接成功,是什么原因造成的呢?

**Comment by zyallday** [comment]
已经解决,在 china_chnroute 文件中添加局域网 192.168.0.0/16即可

**Comment by aa65535** [comment]
ss-rules 中已经排除了 192.168.0.0/16 之类的内网IP
