### ISSUE TITLE
更新到v2.2.3后我的chromecast无法播放了

### ISSUE THREAD

**Issue by polong** [shadowsocks/openwrt-shadowsocks#120]
折腾半天折腾回v2.2.2恢复正常。

**Comment by aa65535** [comment]
DNS 污染，没有启用 UDP中继？

**Comment by polong** [comment]
我回家试试，问题是我有装ChinaDNS，而且我2.2.2是正常的。

**Comment by polong** [comment]
经试验，2.2.3应该有问题，因为2.2.3在正常状态下，chromecast很难进入可以正常连接的状态，比如youtube投射时，会卡在红色youtube图标的启动界面非常久才能进入可播放状态，但是进入可播放状态后是能正常播放的，而完全相同的设置下，2.2.2那个启动界面几乎一闪而过，就直接可以播放了。

**Comment by polong** [comment]
好吧，先收回，好像与我的网络有关，我再试试

**Comment by aa65535** [comment]
chromecast 的DNS是 8.8.8.8 吧。

2015年8月9日 16:31于 polong <notifications@github.com>写道：
我回家试试，问题是我有装ChinaDNS，而且我2.2.2是正常的。

---

**Comment by clowwindy** [comment]
可以在你的局域网里 dig @8.8.8.8 www.youtube.com 看看

**Comment by polong** [comment]
在win下就是nslookup吧，很明显的2.2.3会污染，2.2.2不会。

**Comment by polong** [comment]
经过几天的试验，我再次确定，在相同配置的情况下，2.2.3的确有问题。

**Comment by wongsyrone** [comment]
至少要把测试的输出贴出来吧，纯描述的话大神也没法帮你解决。
