### ISSUE TITLE
更新后不支持非数字的服务器地址了？

### ISSUE THREAD

**Issue by xianbing537** [shadowsocks/openwrt-shadowsocks#124]
更新后不支持非数字的服务器地址了？

**Comment by heyggu** [comment]
是的，感觉还是域名地址挺方便的

**Comment by cielpy** [comment]
是啊。一下子感觉好不方便，因为网络时好时差，经常要换服务器，之前可以使用配置文件，直接覆盖掉文件然后重启服务就好了，现在要手动改文件，就算配置uci也感觉没有之前方便了。不知道为什么去掉使用配置文件这个用法呢。@aa65535

**Comment by aa65535** [comment]
不支持使用域名了

**Comment by clowwindy** [comment]
如果使用域名，那会出现先有鸡还是先有蛋的问题，所以这个域名的解析走不了 Shadowsocks，将暴露你在翻墙。所以请使用 IP。各文档和客户端这一栏也一直叫服务器 IP。

**Comment by cielpy** [comment]
懂了。用ip也解决了用域名当服务器地址的时候如果需要重启ss得先换个可用的DNS的麻烦，用ip的话就不用了。

**Comment by thank243** [comment]
但是使用国内节点tcp加速服务，比如微林，加速节点直接给的是域名，有时候会更换ip。这样的加速服务应该不会出现先有鸡还是先有蛋的问题。所以一巴掌拍死了感觉不太好。

**Comment by wsxy162** [comment]
README.md 上面写的还是可以填写域名，没有修改掉。

**Comment by pexcn** [comment]
设置延迟启动 https://github.com/shadowsocks/luci-app-shadowsocks/commit/f74c185dc9530b8b4f60df8f6395cc94e9e22d3d 之后是否可以用域名了呢？@aa65535

**Comment by aa65535** [comment]
@pexcn 不可以，那个「域名」是 ss-redir 这些支持的。
