### ISSUE TITLE
the options use_config_file & config_file are ignored (or removed ?) since 2.2.3

### ISSUE THREAD

**Issue by kiffer** [shadowsocks/openwrt-shadowsocks#126]
This was my config file /etc/config/shadowsocks , I put ss server configurations in /etc/shadowsocks/config.json 

config shadowsocks
	option enable '1'
	option use_conf_file '1'
	option config_file '/etc/shadowsocks/config.json'
	option ignore_list '/etc/shadowsocks/ignore.list'
	option tunnel_port '5300'
	option tunnel_forward '8.8.4.4:53'
	option lan_ac_mode '0'
	option tunnel_enable '0'
	option udp_relay '1'

Since 2.2.3, even with use_config_file turned on and config_config assigned correctly, it always gives error "/etc/rc.common: line 1: server: parameter not set or null" when starting the service.

the configuration in /etc/shadowsocks/config.json is always ignored and have to config everything in /etc/config/shadowsocks.

**Comment by aa65535** [comment]
These options have been discarded.
