### ISSUE TITLE
路由上用了chinadns来做dns处理，ss-tunel就没必要用了吧

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/openwrt-shadowsocks#128]
ss-tunel仅仅是通过udp转发dns的查询对吧，那个luci标题是UDP转发，可能会误导（当然前提是我的理解是对的话）。建议可以改下DNS查询通过UDP转发。

**Comment by aa65535** [comment]
提供 DNS 查询是 ss-tunnel 的一种用法，之所以要用它，就是让它作为 ChinaDNS 上游服务器使用的，达到线路优化效果。
