### ISSUE TITLE
ss-local和ss-redir可否使用同一套配置？

### ISSUE THREAD

**Issue by Anyfc** [shadowsocks/openwrt-shadowsocks#131]
现在使用的shadowsocks服务端是商家的，商家没有开放DNS转发，单独安装shadowsocks-libev-spec就不能使用ss-tunnel转发DNS，目前的想法是再安装一个ss-local来提供socks5给DNS2socks来解决DNS污染。
但是实际操作中ss-local和ss-redir却不能使用同一套配置，或者说同一个端口，这样操作起来就多一个配置文件和几步命令设置。
那么ss-local可否像ss-tunnel一样使用和ss-redir相同的配置文件？

**Comment by aa65535** [comment]
spec 没有带 ss-local
事实上， ss-tunnel 也没有和 ss-redir 使用完全相同的配置，额外使用 `-l` 指定不同的端口即可。
