### ISSUE TITLE
使用OpenWRT版连接服务器端需要特殊设置？

### ISSUE THREAD

**Issue by Aivier** [shadowsocks/openwrt-shadowsocks#136]
服务器已开启firewalld，但是路由器上的客户端无法使用，关闭firewalld后正常，但是打开firewalld的时候除了openwrt版以外python版，android版，windows版，libev版都是正常的，只有openwrt版无法正常工作

需要在服务器上做什么特殊设定？

**Comment by aa65535** [comment]
并没有什么不同。
