### ISSUE TITLE
有时候会突然断开

### ISSUE THREAD

**Issue by Phishion** [shadowsocks/openwrt-shadowsocks#139]
使用的是2.3.1-1版本，表现为突然会无法连接，国内网站正常，需要翻墙的网站一律无法打开，过几分钟左右又会自行恢复，重启之后也可以立即恢复

- 出问题的时候切到PC版本的SS是正常的（排除服务器问题）
- 出问题的时候手机也一样无法连接（排除PC机的问题）

不知道日志在哪看的，无法提供更多的信息了

**Comment by aa65535** [comment]
查看系统日志就可以了，详细的日志需要修改 `/etc/init.d/shadowsocks` 在命令后添加 `-v` 参数。

**Comment by Phishion** [comment]
你好，我这一块儿不是很熟悉，经过自行搜索研究后也没找到修改``/etc/init.d/shadowsocks``开启日志的方法，能否详细点，谢谢了

**Comment by aa65535** [comment]
在文件 `/etc/init.d/shadowsocks` 中找到 `/usr/bin/ss-tunnel ` 和 `/usr/bin/ss-redir` 在他们后面 `\` 之前加上 `-v`

**Comment by ohyeah521** [comment]
@aa65535 ，确实输出这个问题，我下载android源码，下载了3天了。总是经常路由器莫名奇妙的不能翻墙，重启后恢复正常。

**Comment by Phishion** [comment]
最近一直没有再出现这个问题，还是没找到原因

**Comment by pexcn** [comment]
我抓的日志  https://github.com/shadowsocks/openwrt-shadowsocks/issues/106#issuecomment-153778230
