### ISSUE TITLE
OpenWrt自动翻墙有时无效的问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/openwrt-shadowsocks#150]
在openwrt配置自动翻墙，shadowsocks-libev-spec+chinadns的方案，区分内外流量。
但是有时自动翻墙会无效，走了代理的网站都打不开。过了十几分钟作用又自动好了。这种情况几乎每天都发生几次，有时候重启下网络换下新的IP就好了，有时则不行，不知道是ss的问题还是chinadns的问题或是openwrt的问题?

**Comment by ohyeah521** [comment]
貌似是ss的问题，我也有这样的问题，不知道什么问题，不好使的时候就重启路由器或者进入路由里面输入 /etc/init.d/shadowsocks  restart

**Comment by pexcn** [comment]
我有时候重启网络就会好了，有时不行，不知道是不是ip的问题

**Comment by pexcn** [comment]
好像也是 https://github.com/shadowsocks/openwrt-shadowsocks/issues/106 这个问题

**Comment by pexcn** [comment]
拿ar71xx架构的旧路由测试了几天，都没这个问题。
ramips的版本的ss倒是有问题。
