### ISSUE TITLE
ss-rule脚本优化的小提议

### ISSUE THREAD

**Issue by Sakura-Winkey** [shadowsocks/openwrt-shadowsocks#154]
目前重启防火墙时，会连带执行/etc/init.d/shadowsocks rule命令（即ss-rule脚本），导致每次重启防火墙时间略长（3~4秒左右）
这可能是脚本中有几个for循环的关系
所以提议执行完ss-rule后，在/var目录生成一个关于SS_SPEC的防火墙规则文件，再include到firewall的config文件中
所生成的防火墙规则脚本类似
```
iptables -t nat -N SS_SPEC_WAN_FW
iptables -t nat -A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_ac dst -j RETURN
...... 
```

感觉这样比暴力地再执行/etc/init.d/shadowsocks rule会快（尤其在支持ipset的设备上更明显！）

**Comment by aa65535** [comment]
没有必要， ss-rules 执行速度足够快。
