### ISSUE TITLE
关于SS-RULES

### ISSUE THREAD

**Issue by reusu** [shadowsocks/openwrt-shadowsocks#156]
参数中的-u和-U有什么区别
使用不同的ip和port是什么意思
也就是说本地可能建了两套ss-redir？
P1的ip是x.x.x.x 监听在a端口 只提供tcp服务
P2的ip是o.o.o.o 监听在b端口 提供tcp+udp服务
那么我想tcp通过P1 udp通过p2的话
是不是这样
ss-rules -s x.x.x.x -l a -S o.o.o.o -L b -i /dev/null -U -o

**Comment by aa65535** [comment]
关于 ss-redir 的 `-u` 与 `-U` 参考 [这里](https://github.com/shadowsocks/shadowsocks-libev#usage)

而 ss-rules 的 `-u` 与 `-U` 只是为了支持 ss-redir, 
如果使用 `-u` 的话则使用与 TCP 模式相同的 IP:PORT 提供 UDP, 同时需要 ss-redir 使用 `-u` 参数，一般是使用单个 ss-redir 进程提供 TCP 和 UDP。
如果使用 `-U` 的话则不使用 TCP 模式提供的 IP:PORT代理  UDP（需要另外使用 -S 和 -L 指定）, 此时需要 ss-redir 使用 `-U`或者 `-u` 参数打开UDP功能，一般是建立两个 ss-redir 进程分别提供 TCP 和 UDP。
