### ISSUE TITLE
能否给出一个转发udp数据的iptables例子？不是udp查询，是转发所有udp数据。

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/openwrt-shadowsocks#157]
一直没明白专门转发udp数据，luci界面的那个udp转发是转发的udp查询吧？转发地址是谷歌的dns服务器。

**Comment by aa65535** [comment]
UDP中继

**Comment by hdstar2009** [comment]
你的回复我看了还是没明白。
udp中继不是两个ss服务器之间中继数据吗。例如通过一个国内的ss服务器来中转。
难道luci界面的udp中继选择其实就可以转发所有的udp数据了？
