### ISSUE TITLE
最新的 2.4.0-1 在 OpenWRT trunk 上 -ash: ss-XXXX: not found

### ISSUE THREAD

**Issue by VcamX** [shadowsocks/openwrt-shadowsocks#159]
在 /usr/bin/ 目录下这些程序均存在，但是运行都显示

-ash: ss-local: not found
-ash: ss-redir: not found
-ash: ss-tunnel: not found

下载 trunk 的 SDK 自行编译安装也是这个错误，不知是什么原因

**Comment by river1** [comment]
我今天也遇到了这个问题，请问你是怎么解决的

**Comment by VcamX** [comment]
@river1 我后来直接用 [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev)

**Comment by rayhu** [comment]
ls -al 看执行文件的权限
如果没有 x，可以 chmod 755 去给他们加上
