### ISSUE TITLE
如何忽略所有IP？

### ISSUE THREAD

**Issue by ExinCoda** [shadowsocks/openwrt-shadowsocks#160]
ignore.list里面尝试写了
0.0.0.0/0
保存ignore.list，LuCI里显示状态为shadowsocks not running

**Comment by ExinCoda** [comment]
不想关闭shadowsocks，因为需要用于ChinaDNS

**Comment by aa65535** [comment]
```
0.0.0.0/1
128.0.0.0/1
```

**Comment by ohyeah521** [comment]
@ExinCoda  用 ss 配合 Chinadns 非常坑，前几天 ss 挂掉了，结果导致路由器只能上QQ，打不开网页，后来慢慢排除才发现是ss的问题。

**Comment by ExinCoda** [comment]
@ohyeah521 你的ChinaDNS的DNS列表里是不是只有ss的监听地址？添加其他DNS地址应该可以避免这个情况
