### ISSUE TITLE
Openwrt+Shadowsocks-libev 2.4.0-1运行一段时间不能翻墙，国内网站可以打开。

### ISSUE THREAD

**Issue by jack338c** [shadowsocks/openwrt-shadowsocks#165]
Openwrt+Shadowsocks-libev 2.4.0-1 运行一段时间后，不能翻墙，国内网站可以打开。

重启路由器可以解决问题，而RESTART Shadowsocks 或 RESTART CHINADNS 基本上候解决不了问题。

究竟怎么样才能解决这个问题？

注：UDP Forward enable  ,UDP Relay  enable
OpenWrt Chaos Calmer 15.05 / LuCI (git-15.248.30277-3836b45)

**Comment by ohyeah521** [comment]
这个问题是chinadns的问题，你重启chinadns就可以了。/etc/init.c/chinadns restart    你可以试试。

**Comment by jack338c** [comment]
@ohyeah521 
好的，我到时试试看
另外请教：UDP RELAY 和 UDP Forward 启用还是不启用好，这个不懂

**Comment by aa65535** [comment]
不是必须的话不要启用 UDP

**Comment by ohyeah521** [comment]
@jack338c  如果你需要用 ss 进行域名解析的话，就打开udp，否则就关闭它，去掉那个 -u的启动参数即可。

**Comment by flipphos** [comment]
������Plex Media Server (PMS)��Remote access��������ss server��ip������������������������������������������
��������plex.tv������ip����ss����������������������
����������������
