### ISSUE TITLE
尚未尝试，先来讨教：IP表示方法

### ISSUE THREAD

**Issue by hahahahahuo** [shadowsocks/openwrt-shadowsocks#168]
“使指定的 IP 不被 SS 代理”中，支持前缀表示方法么？IPv6能读懂不？这两个问题综合起来，用

::/128

能否表示所有IPv6地址？
目的就是所有非DNS的IPv6流量都不被代理。
谢谢！

**Comment by aa65535** [comment]
https://www.ultratools.com/tools/ipv6CIDRToRange
