### ISSUE TITLE
“仅允许列表内”功能似乎无效

### ISSUE THREAD

**Issue by forver8023** [shadowsocks/openwrt-shadowsocks#171]
开启了透明代理，但是只想给我的电视盒子跟笔记本使用，但是开启了“仅允许列表内”并填上了设备的ip，发现所有设备都是在走这个透明代理，包括没有填在ip列表里的设备。

请问如何解决？ipset save ss_spec_lan_ac的记录是这样的
#ipset save ss_spec_lan_ac
create ss_spec_lan_ac hash:net family inet hashsize 1024 maxelem 65536
add ss_spec_lan_ac 192.168.1.101 nomatch
add ss_spec_lan_ac 192.168.1.189 nomatch

非常感谢！

**Comment by sjtuross** [comment]
是否能发布一次编译好的新版本，急需使用这个功能，谢谢！

**Comment by aa65535** [comment]
@sjtuross 手动替换一下 /usr/bin/ss-rules 的内容就行了
https://github.com/shadowsocks/openwrt-shadowsocks/blob/master/files/shadowsocks.rule
