### ISSUE TITLE
openwrt的client请加上 ss-local 和 ss-server

### ISSUE THREAD

**Issue by mzhboy** [shadowsocks/openwrt-shadowsocks#176]
如题，不光op上没有这两个不方便，依赖op的entware-ng那边也没有 `ss-local` `ss-server`。很不方便的

**Comment by aa65535** [comment]
在 shadowsocks-libev 中是包含 ss-local 的，既然是 client，就不会添加 ss-server。

**Comment by mzhboy** [comment]
然而 https://github.com/openwrt/packages/blob/master/net/shadowsocks-libev/Makefile#L78
这里并没有 `ss-local`, 另外我也会把路由做服务端用的，所以还是加上 `ss-local` 吧，起码给个可选的安装项。现在我也没有精力自己编译这些包了。

**Comment by MercuryhgJiang** [comment]
也请加入SS-LOCAL，并不是全部都需要进行代理。原来使用SS-LOCAL一直很好，按需要使用代理，而现在却找不到了。
