### ISSUE TITLE
路由器需要7*24小时运行

### ISSUE THREAD

**Issue by fshh1988** [shadowsocks/openwrt-shadowsocks#181]
路由器需要7*24小时运行，但是经常碰到SS断线的问题，需要重新手动重启SS
要是能添加心跳机制和断线重连是不是更稳妥一点呢，免去使用的困扰

**Comment by ohyeah521** [comment]
不能加入心跳，这样会出现明显特征，导致服务器被认证

**Comment by zhaojunmo** [comment]
没有重连机制的吗？那使用起来还是非常不方便

**Comment by Anyfc** [comment]
写个守护脚本？

**Comment by zhaojunmo** [comment]
如果写守护脚本的话会不会导致 @ohyeah521 说的明显特征？

**Comment by Anyfc** [comment]
https://cokebar.info/archives/850#part3
我最近也出现了openwrt端经常断线，而其他客户端正常的现象，使用这个脚本后缓解了一些，
你试试吧，我的看log一天下来，有20多次重启的。。。

**Comment by zhaojunmo** [comment]
@Anyfc 非常感谢
