### ISSUE TITLE
可以增加 Server 端的控制吗？

### ISSUE THREAD

**Issue by PeterTPE** [shadowsocks/openwrt-shadowsocks#182]
有可能增加 Server 端的控制吗？这样只要有路由器就可以架设 Server 了！

**Comment by ohyeah521** [comment]
没必要这样弄，都是部署到国外的机器上，搞到路由器上没意义，也浪费维护的时间成本。

**Comment by mengskysama** [comment]
需要打包server到ipk只要修改下makefile就行了或者直接从编译临时文件夹里拿出来。

**Comment by PeterTPE** [comment]
因为一些台湾来的朋友，家里都有闲置的光纤线路，不利用太可惜了
2015/12/18 下午8:32於 "ohyeah521" <notifications@github.com>寫道：

**Comment by PeterTPE** [comment]
我自己没有相关的经验，但会自己试试看的，谢谢指导！
2015/12/18 下午10:34於 "mengskysama" <notifications@github.com>寫道：

**Comment by aa65535** [comment]
No plan for this.
