### ISSUE TITLE
ss-rules[6743]: Can't redirect, please check the iptables.

### ISSUE THREAD

**Issue by hansonhu** [shadowsocks/openwrt-shadowsocks#183]
更新到最新版2.4.3_ar71xx后，启动提示
ss-rules[6743]: Can't redirect, please check the iptables.

\# iptables -V
iptables v1.4.10

非 AP 模式运行
路由型号	NETGEAR WNDR3700v2
固件版本	OpenWrt Attitude Adjustment 12.09 / LuCI 0.11.1 Release (0.11.1)
内核版本	3.3.8

**Comment by aa65535** [comment]
不支持 REDIRECT,  可以试试 
```sh
iptables -t nat -A SS_SPEC_WAN_FW -p tcp -j DNAT --to-destination $local_ip:$local_port
```
local_ip 是路由的 LAN IP

**Comment by sbugzu** [comment]
更新 OpenWrt 到最新版本，问题解决
