### ISSUE TITLE
一次验证问题

### ISSUE THREAD

**Issue by i0sdev** [shadowsocks/openwrt-shadowsocks#184]
升级了到了`shadowsocks-libev-spec 2.4.3-1`，发现设置里有`一次验证`，选中后就不能翻了。这个是要服务器端也要做相应设置吗？怎么弄？谢谢！

**Comment by aa65535** [comment]
shadowsocks/shadowsocks-libev#428

需要服务端同时开启此功能

**Comment by i0sdev** [comment]
看了最后一个链接里的代码，'auth'部分，试着在服务器端加了'"auth":true'不行，'"auth":"hmac-sha256"'也不行。正确的写法应该是什么？

**Comment by aa65535** [comment]
@i0sdev 命令行上加个 `-A` 参数

**Comment by i0sdev** [comment]
@aa65535 我确实这么弄的，路由器上openwrt版本的里面选中`一次验证`，vps上的版本是最新的`2.8.2`，json配置文件里加上`"auth": true.`重启服务后，该翻就是不能连上，浏览器也没什么提示。

**Comment by aa65535** [comment]
@i0sdev Python 版本不支持OTA, 实现在 auth 分支里, 并未合并到 master.

**Comment by DreamSeason** [comment]
Any OS X client which support OTA?
