### ISSUE TITLE
LAN muti-policy control support

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/openwrt-shadowsocks#188]
situation is that different devices in a LAN need their own proxy policy:
PC, smartphones: chn IP bypass mode
PS4: global
download machine: bypass all

any advices?
write this kind of custom iptable rules is a little bit difficult for me

**Comment by aa65535** [comment]
This feature may be added in the future.

**Comment by GuBo88** [comment]
I have the same request. And looking forward for this enhancement.

**Comment by cokebar** [comment]
GJ!
