### ISSUE TITLE
opkg install shadowsocks-libev-spec_2.4.3-1_ar71xx.ipk

### ISSUE THREAD

**Issue by zzx2010zx** [shadowsocks/openwrt-shadowsocks#191]
openwrt cc 15.05下 opkg install shadowsocks-libev-spec_2.4.3-1_ar71xx.ipk
提示Collected errors:
 * deb_extract: shadowsocks-libev-spec_2.4.3-1_ar71xx.ipk: invalid magic
 * pkg_init_from_file: Failed to extract control file from shadowsocks-libev-spec_2.4.3-1_ar71xx.ipk. 初学 不懂 谷歌找不到解决方法

**Comment by heshiming** [comment]
看上去是文件下载错误或者不完整，你要从靠谱的地方重新下载。

**Comment by zzx2010zx** [comment]
http://sourceforge.net/projects/openwrt-dist/files/shadowsocks-libev/2.4.3-33429ad/ar71xx/ 这里下载的

**Comment by aa65535** [comment]
如 @heshiming 所说, 是因为下载的文件不完整.

**Comment by zzx2010zx** [comment]
可是 怎么会不完整呢 我重新下了无数次 还是这样啊

**Comment by zzx2010zx** [comment]
已解决 重复下载多次才解决了
