### ISSUE TITLE
使用最新的openwrt14.07 trunk源码build出来的SDK打包openwrt-shadowsocks出错

### ISSUE THREAD

**Issue by ncisoft** [shadowsocks/openwrt-shadowsocks#192]
错误信息如下：
Package shadowsocks-libev is missing dependencies for the following libraries:
libcrypto.so.1.0.0
libpthread.so.0
libz.so.1
Makefile:109: recipe for target '/home/leeyg/ports/openwrt-sdk/bin/ar71xx/packages/base/shadowsocks-libev_2.4.3-1_ar71xx.ipk' failed

只选了shadowsocks-libev一个包
怀疑是SDK增强了ipk打包检查，以前老版本的SDK能正常打包

**Comment by aa65535** [comment]
shadowsocks/shadowsocks-libev#463
