### ISSUE TITLE
openwrt中chinadns+shadowsocks代理失败

### ISSUE THREAD

**Issue by wyxls** [shadowsocks/openwrt-shadowsocks#195]
服务端设置没问题，查看log也是运转正常(用的breawa11的Python的服务端，配置了auth_sha1协议和混淆)

路由器刷好了chinadns+shadowsocks，chinadns占用端口5353，上游223.5.5.5,127.0.0.1:5354(udp转发)

shadowsocks设置没错，本地端口1080，udp转发端口5354

DNS转发为chinadns端口5353

chinadns运作正常，路由器内shadowsocks也能正常接收chinadns的dns解析请求(国内网站域名和IP都能正常解析访问)

然后问题就是无法实现国外代理，好像是路由器转发流量到服务端无效？

服务端log没有任何tcp和udp连接提示，服务端曾换回clowwindy的python版测试，依然没有任何请求从路由发送到服务端)

不仅是UDP请求没反应，连TCP也没反应，是否防火墙和Qos配置问题？

**Comment by aa65535** [comment]
不支持你所说的混淆

**Comment by wyxls** [comment]
不是，我是试过原本无混淆的python ss，但依然出现同样的问题

**Comment by aa65535** [comment]
大概是服务端和客户端配置不一致, Python 版 master 分支下的版本并没有支持 OTA, libev版不支持混淆.

**Comment by wyxls** [comment]
pip install shadowsocks默认装的是python版？

意思是我需要在服务端编译一个libev版的？

**Comment by aa65535** [comment]
配置问题, 如果启用 OTA 的话 两端需要同时启用.

**Comment by wyxls** [comment]
(╯﹏╰)b，没懂OTA是什么

**Comment by yhzero** [comment]
上面提到kmod内核是啥东西？？我今天刚用 trunk 编译的 都是这样连不上去 貌似有这问题的人很少？
