### ISSUE TITLE
shadowsocks和chinadns无法启动

### ISSUE THREAD

**Issue by nibaren2012** [shadowsocks/openwrt-shadowsocks#197]
openwrt是snapshots      git-15.324.84666-55f4583

/etc/init.d/shadowsocks start 出现：
/etc/rc.common: line 1: /usr/bin/ss-redir: not found

启动chinadns 没有报错  但是在luci 那里看到 chinadns 没有启动

**Comment by aa65535** [comment]
`ls -l /usr/bin/ss-redir` 如果文件存在, 且有可执行权限, 说明不支持此路由器架构, 可以自己使用对应的 SDK 编译一个.
