### ISSUE TITLE
shadowsocks集成到固件里无法运行。

### ISSUE THREAD

**Issue by nibaren2012** [shadowsocks/openwrt-shadowsocks#202]
自己编译的snapshots的固件，clone了你这里的代码，还有chinadns的。编译好后刷入机器，发现chinadns是可以运行的，但是ss不行，然后装了luci-app-shadowsocks-spec_1.3.7-1_all.ipk 
出现这样的图。
![default](https://cloud.githubusercontent.com/assets/9211399/12357118/1f9d3a20-bbe1-11e5-8275-356f60ce6691.PNG)

**Comment by aa65535** [comment]
#196

**Comment by nibaren2012** [comment]
我将集成的ss删掉，旧版 /etc/config/shadowsocks 也移除了，然后再在编译固件时的目录里找到shadowsocks-libev-spec_2.4.3-1_ramips_24kec.ipk，重新上传路由器安装。发现和刚开始集成的时候是一样的状况。没有报错信息。
![1](https://cloud.githubusercontent.com/assets/9211399/12369698/697cd7e4-bc37-11e5-82bc-3bde4f719397.PNG)
