### ISSUE TITLE
configuraiton file issue

### ISSUE THREAD

**Issue by piero66** [shadowsocks/openwrt-shadowsocks#203]
does any one know why the configuration file with the application installed from precompiled file is different from the one installed with compiled file myself?

precompiled ipk configuration file,

config shadowsocks
        option local_port '1080'
        option timeout '60'
        option encrypt_method 'rc4-md5'
        option udp_mode '0'
        option tunnel_port '5300'
        option tunnel_forward '8.8.4.4:53'
        option lan_ac_mode '0'
        option enable '1'
        option auth_enable '0'
        option server ''
        option server_port ''
        option password ''
        option ignore_list '/etc/chinadns_chnroute.txt'
        option tunnel_enable '0'

compiled ipk myself configruation file,

config global
        option global_server 'nil'

config servers
        option auth_enable '0'
        option server '127.0.0.1'
        option server_port '8388'
        option local_port '1080'
        option password 'barfoo!'
        option timeout '60'
        option encrypt_method 'rc4-md5'

config udp_forward
        option tunnel_enable '0'
        option tunnel_port '5300'
        option tunnel_forward '8.8.4.4:53'

config access_control
        option lan_ac_mode '0'
        option wan_bp_list '/dev/null'

**Comment by aa65535** [comment]
[v2.4.4](https://github.com/shadowsocks/openwrt-shadowsocks/releases/tag/v2.4.4)
