### ISSUE TITLE
新版怎么用？

### ISSUE THREAD

**Issue by suikatomoki** [shadowsocks/openwrt-shadowsocks#205]
变化好大啊，我都找不到填udp转发和忽略代理的地方

![xshot-0057](https://cloud.githubusercontent.com/assets/10336224/12510781/50a7284a-c147-11e5-9f80-827271909178.png)

**Comment by suikatomoki** [comment]
我暂时回退到 luci-app-shadowsocks-spec_1.3.7-1 与 shadowsocks-libev-spec_2.4.3-1 了

**Comment by aa65535** [comment]
因为在 2c8d01a 添加了多服务器的支持, 所以 /etc/config/shadowsocks 文件结构有所改变, 不能使用旧版的了, 可以尝试将旧版 /etc/config/shadowsocks 移除, 因为卸载或者直接更新是不会移除这个文件的.

**Comment by suikatomoki** [comment]
@aa65535 感谢，删掉后正常
