### ISSUE TITLE
2.44忽略IP列表无法正常工作

### ISSUE THREAD

**Issue by heyggu** [shadowsocks/openwrt-shadowsocks#206]
更新到2.44后，因在教育网环境，By Pass掉下列教育网IP后无法正常工作了，2.43却无此问题。劳驾检查一下。
[chnroute_edu.txt](https://github.com/shadowsocks/openwrt-shadowsocks/files/100872/chnroute_edu.txt)

**Comment by aa65535** [comment]
不再支持使用注释了, 删掉L61 的注释.

**Comment by DreamSeason** [comment]
我也在教育网，是从61起后面都是教育网？

**Comment by heyggu** [comment]
@DreamSeason 刚看了下比较杂乱且不全，根据http://www.nic.edu.cn/RS/ipstat/internalip/real20160116.html又做了一份
[edu_ip.txt](https://github.com/shadowsocks/openwrt-shadowsocks/files/102741/edu_ip.txt)

**Comment by heyggu** [comment]
@DreamSeason 刚看了下比较杂乱且不全，根据http://www.nic.edu.cn/RS/ipstat/internalip/real20160116.html  又做了一份
[edu_ip.txt](https://github.com/shadowsocks/openwrt-shadowsocks/files/102742/edu_ip.txt)

**Comment by DreamSeason** [comment]
这个真复杂。 不知道这些在ChinaDNS里面覆盖了没有。
