### ISSUE TITLE
No ignore list in new luci 1.3.8?

### ISSUE THREAD

**Issue by muronghan** [shadowsocks/openwrt-shadowsocks#208]
Hi, I updated to shadowsocks-libev-spec 2.4.4.1 and luci 1.3.8 all on my WRT1200ac OpenWrt cc-final. However, I could not find the column of ignore list which exists on previous luci 1.3.7. How could I setup chinaroute strategy for ss in OpenWrt router?

**Comment by aa65535** [comment]
Access Control --> WAN --> Bypassed IP List

**Comment by muronghan** [comment]
thanks a lot

**Comment by DreamSeason** [comment]
Is it the same one as ChinaDNS?
