### ISSUE TITLE
安装后ash报找不到可执行文件

### ISSUE THREAD

**Issue by acabin** [shadowsocks/openwrt-shadowsocks#213]
#149 #159 #166 
全都指向了同一个错误：
明明指定了可执行文件的路径，但是ash仍然会报not found
本人测试，从2.3.3到2.4.4全都无法正常使用。
表现：
```
# ss-redir
ash: ss-redir: not found
# which ss-redir
/usr/bin/ss-redir
```
系统版本：trunk r48548

**Comment by muronghan** [comment]
这个版本是基于r46767编译的吧，应该不支持trunk？

**Comment by blog2i2j** [comment]
目前aa编译的ss是基于libc的, op的trunk已经放弃libc了, 所以没法使用.

**Comment by aa65535** [comment]
目前提供的预编译ipk是使用15.05的SDK编译的，如果不支持还是自己下载对应的SDK编译一下吧。

**Comment by muronghan** [comment]
请问op下的shadowsocks-libev-spec，是否近期有支持musl-libc的打算？
