### ISSUE TITLE
建议在gen_iplist()函数中增加空行防错

### ISSUE THREAD

**Issue by blog2i2j** [shadowsocks/openwrt-shadowsocks#215]
aa65535好
我在使用2.4.4的spec版本时发现ipset会出错, 经过检查发现是gen_iplist函数中的cat <<-EOF 没有去空行功能, 如果列表中包含了空格, 就会出错. 建议在cat << -eof后增加grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"

**Comment by aa65535** [comment]
这个是考虑到性能取消了非IP地址行的过滤，因为忽略列表一般是使用自动生成的ChinaDNS路由表，是不需要过滤的，如果是自定义的列表，建议自己不要往里面写入非IP行。
