### ISSUE TITLE
Will the new version of Shadowsocks-libev-spec possibly support trunk?

### ISSUE THREAD

**Issue by muronghan** [shadowsocks/openwrt-shadowsocks#218]
As the development of cc trunk has been transferred to a new platform, which the current ss does not support. Meanwhile, CC final works fine basically however its wireless driver has dozens of bugs. Those bugs are not reported or observed on Trunk. 

Therefore, it might be very helpful if the next version of ss could support Trunk. Thanks a lot in advance! And Happy Chinese New Year!

**Comment by muronghan** [comment]
Tried to compile shadowsocks-libev-spec.ipk today upon the recent trunk, but it failed.

**Comment by aa65535** [comment]
Compile it yourself.

**Comment by muronghan** [comment]
ss complied upon trunk r49005 (kernel 4.1.6) successfully.
