### ISSUE TITLE
无法播放nico的视频

### ISSUE THREAD

**Issue by cooku** [shadowsocks/openwrt-shadowsocks#221]
https://cokebar.info/archives/664/
我是使用上面这篇文章的教程来在家翻墙的，然而一直不能正常观看nico的视频。
但是我如果我在手机上用vpn再次翻到日本ip，就能正常播放。
不知道是什么问题...

**Comment by aa65535** [comment]
先排除 DNS 的问题。

**Comment by cooku** [comment]
嗯.
