### ISSUE TITLE
目前shadowsocks-libev-spec是否能支持自动分流

### ISSUE THREAD

**Issue by w0330t** [shadowsocks/openwrt-shadowsocks#222]
如题，目前我用 的非SPEC版本，用dnsmasq分流，我就想问问直接装一个SPEC版本是否可行？

**Comment by aa65535** [comment]
请说明一下非 spec 时是如何配置的

**Comment by w0330t** [comment]
目前我采用 [https://cokebar.info/archives/962](url) 的方法，DNS采用链接内的方案一实现。

**Comment by aa65535** [comment]
建议继续使用非 spec 版本，使用 spec 版本需要修改的东西比较多，并不如非 spec 版方便。
