### ISSUE TITLE
能否实现 shadowsocks for Android 的 IPv6 Route 功能？

### ISSUE THREAD

**Issue by dansean** [shadowsocks/openwrt-shadowsocks#225]
能否实现 shadowsocks for Android 的 IPv6 Route 功能？
      最近试验了一下 Android 的 Redirect IPv6 traffic to remote 功能，比国内 6to4 快很多。
所以问一下有空能否实现这个功能，感激不尽！

**Comment by cokebar** [comment]
this repo use NAT, which is not supported in IPV6.

**Comment by aa65535** [comment]
no plan for this.
