### ISSUE TITLE
希望在shadowsocks-libev-spec服务器地址栏里加入域名地址的支持

### ISSUE THREAD

**Issue by biankasyo** [shadowsocks/openwrt-shadowsocks#226]
希望在shadowsocks-libev-spec服务器地址栏里支持填入域名地址，小弟的ss服务端运行在动态ip的服务器上，ss客户端通过ddns域名解析后获得服务端ip地址进行通信，而spec貌似并不支持在服务器地址栏中输入域名并解析，在luci中填入提示格式错误，手动修改/etc/config/shadowsocks配置文件并运行，也无法连通，希望LZ支持 (๑•̀ㅂ•́)و✧

**Comment by seyrenhe** [comment]
这个以前有人问过，之所以不支持域名，是先有鸡还是先有蛋的问题，搜一下吧。

**Comment by xdrwedc** [comment]
我也傻了，以前购买的ss服务只提供了网址，没有IP地址。好在Ping出来的IP可以用，但不过不知道会不会经常变。
