### ISSUE TITLE
能否对shadowsocks-rss做个openwrt的客户端？

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/openwrt-shadowsocks#227]
https://github.com/breakwa11/shadowsocks-rss

最近试用了，发现这个的混淆等手段确实对访问速度有明显提升。
比如我刚刚访问vultru伦敦的节点，用普通不开混淆端口的话看youtube视频速度几百k，也提升不上来。换到有混淆的端口，同样的youtube视频速度立马是2k多，而且可以慢慢提升上来。

但是没看到有人做openwrt下的客户端。

**Comment by aa65535** [comment]
no plan for this
