### ISSUE TITLE
为什么已经设了全局代理了，还会有很多不走代理的TCP链接

### ISSUE THREAD

**Issue by DragonCat1** [shadowsocks/openwrt-shadowsocks#228]
版本：shadowsocks-libev-spec 	2.4.5-1
被忽略IP列表：留空-作为全局代理
但是在openwrt-实时信息-链接 里面还能看到很多活动的不经代理的链接
类似
IPV4	UDP	PC-lhg.lan:62821	nuq04s29-in-f14.1e100.net:443
IPV4	TCP	PC-lhg.lan:1992	203.208.43.78:443
IPV4	TCP	PC-lhg.lan:1953	192.64.174.65:2099
IPV4	TCP	PC-lhg.lan:2108	nuq04s19-in-f14.1e100.net:443

**Comment by aa65535** [comment]
即使是「全局代理」，依然会主动忽略一些保留地址和局域网地址的。
