### ISSUE TITLE
小米路由器（R2D）default_postinst: not found无法安装

### ISSUE THREAD

**Issue by kanochen** [shadowsocks/openwrt-shadowsocks#232]
OP版本是 12.09
内核是 2.6.36
搜到: issues 151
https://github.com/shadowsocks/openwrt-shadowsocks/issues/151
但是无法修改functions
求教

**Comment by cokebar** [comment]
OP12.09太老了

**Comment by kanochen** [comment]
@cokebar 我也知道啊，唉。不知道为啥小米要弄个这么老的版本。

**Comment by aa65535** [comment]
#185 
报错好像并不影响安装

**Comment by cokebar** [comment]
@aa65535 我用的GL-iNet的定制版OP固件 CC15.05 RC版的也有这个错误 不仅仅是安装时候 restart以后也会报错但是不影响使用
