### ISSUE TITLE
请提供shadowsocks-libev-full打包

### ISSUE THREAD

**Issue by fanthos** [shadowsocks/openwrt-shadowsocks#233]
在我的配置上希望有些网站自动连接shadowsocks，并且提供手动本地代理功能。现有的两个打包各只提供一部分功能。
希望有一个打包版可以提供 ss-{local,redir,rules,tunnel}

**Comment by cokebar** [comment]
你可以先装个shadowsocks-libev，然后强制覆盖安装shadowsocks-libev-spec版

**Comment by Yusoo** [comment]
我也希望这样，干嘛要分成2个版本呢。
