### ISSUE TITLE
编译时出现找不到 zlib 的错误

### ISSUE THREAD

**Issue by EdiTurn** [shadowsocks/openwrt-shadowsocks#235]
系统: Ubunutu 15.10 x64
SDK: OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64.tar.bz2
         OpenWrt-SDK-15.05-ar71xx-nand_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64.tar.bz2

编译输出：
 #
 # configuration written to .config
 #
make[1]: Entering directory '/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64'
make[2]: Entering directory '/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/package/shadowsocks-libev'
rm -f /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/target-mips_34kc_musl-1.1.14/stamp/.shadowsocks-libev.openssl_installed
(cd /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5; rm -f aclocal.m4; if [ -f ./configure.ac ] || [ -f ./configure.in ]; then [ -d ./autom4te.cache ] && rm -rf autom4te.cache; [ -e ./config.rpath ] || ln -s /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/scripts/config.rpath ./config.rpath; touch NEWS AUTHORS COPYING ABOUT-NLS ChangeLog; AUTOM4TE=/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/autom4te AUTOCONF=/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/autoconf AUTOMAKE=/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/automake ACLOCAL=/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/aclocal AUTOHEADER=/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/autoheader LIBTOOLIZE=/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/libtoolize LIBTOOL=/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/libtool M4=/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/m4 AUTOPOINT=true /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/autoreconf -v -f -i -s -B /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/share/aclocal -I /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/target-mips_34kc_musl-1.1.14/host/share/aclocal -I /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/target-mips_34kc_musl-1.1.14/usr/share/aclocal -I m4 -I . . || true; fi; );
OpenWrt-libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
OpenWrt-libtoolize: linking file `build-aux/ltmain.sh'
OpenWrt-libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
OpenWrt-libtoolize: linking file `m4/libtool.m4'
OpenWrt-libtoolize: linking file `m4/ltoptions.m4'
OpenWrt-libtoolize: linking file `m4/ltsugar.m4'
OpenWrt-libtoolize: linking file `m4/ltversion.m4'
OpenWrt-libtoolize: linking file `m4/lt~obsolete.m4'
OpenWrt-libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `auto'.
OpenWrt-libtoolize: linking file `auto/ltmain.sh'
OpenWrt-libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
OpenWrt-libtoolize: linking file `m4/libtool.m4'
OpenWrt-libtoolize: linking file `m4/ltoptions.m4'
OpenWrt-libtoolize: linking file `m4/ltsugar.m4'
OpenWrt-libtoolize: linking file `m4/ltversion.m4'
OpenWrt-libtoolize: linking file `m4/lt~obsolete.m4'
(cd /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5/./; if [ -x ./configure ]; then find /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5/ -name config.guess | xargs -r chmod u+w; find /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5/ -name config.guess | xargs -r -n1 cp --remove-destination /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/scripts/config.guess; find /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5/ -name config.sub | xargs -r chmod u+w; find /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5/ -name config.sub | xargs -r -n1 cp --remove-destination /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/scripts/config.sub; AR="mips-openwrt-linux-musl-gcc-ar" AS="mips-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5:shadowsocks-libev-2.4.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mips-openwrt-linux-musl-ld NM="mips-openwrt-linux-musl-gcc-nm" CC="mips-openwrt-linux-musl-gcc" GCC="mips-openwrt-linux-musl-gcc" CXX="mips-openwrt-linux-musl-g++" RANLIB="mips-openwrt-linux-musl-gcc-ranlib" STRIP=mips-openwrt-linux-musl-strip OBJCOPY=mips-openwrt-linux-musl-objcopy OBJDUMP=mips-openwrt-linux-musl-objdump SIZE=mips-openwrt-linux-musl-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5:shadowsocks-libev-2.4.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CXXFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=34kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5:shadowsocks-libev-2.4.5 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CPPFLAGS="-I/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/target-mips_34kc_musl-1.1.14/usr/include -I/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/target-mips_34kc_musl-1.1.14/include -I/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/usr/include -I/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/include/fortify -I/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/include " LDFLAGS="-L/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/target-mips_34kc_musl-1.1.14/usr/lib -L/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/target-mips_34kc_musl-1.1.14/lib -L/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/usr/lib -L/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/lib -znow -zrelro "   ./configure --target=mips-openwrt-linux --host=mips-openwrt-linux --build=x86_64-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls   --disable-ssp ; fi; )
configure: loading site script /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/include/site/mips
checking for mips-openwrt-linux-gcc... mips-openwrt-linux-musl-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether mips-openwrt-linux-musl-gcc accepts -g... yes
checking for mips-openwrt-linux-musl-gcc option to accept ISO C89... none needed
checking whether mips-openwrt-linux-musl-gcc understands -c and -o together... yes
checking how to run the C preprocessor... mips-openwrt-linux-musl-gcc -E
checking for grep that handles long lines and -e... /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/grep
checking for egrep... /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mips-openwrt-linux-strip... mips-openwrt-linux-musl-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of mips-openwrt-linux-musl-gcc... gcc3
checking for mips-openwrt-linux-ar... mips-openwrt-linux-musl-gcc-ar
checking the archiver (mips-openwrt-linux-musl-gcc-ar) interface... ar
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-pc-linux-gnu
checking host system type... mips-openwrt-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/sed
checking for fgrep... /tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/host/bin/grep -F
checking for ld used by mips-openwrt-linux-musl-gcc... mips-openwrt-linux-musl-ld
checking if the linker (mips-openwrt-linux-musl-ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... mips-openwrt-linux-musl-gcc-nm
checking the name lister (mips-openwrt-linux-musl-gcc-nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-pc-linux-gnu file names to mips-openwrt-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for mips-openwrt-linux-musl-ld option to reload object files... -r
checking for mips-openwrt-linux-objdump... mips-openwrt-linux-musl-objdump
checking how to recognize dependent libraries... pass_all
checking for mips-openwrt-linux-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for mips-openwrt-linux-ar... (cached) mips-openwrt-linux-musl-gcc-ar
checking for archiver @FILE support... @
checking for mips-openwrt-linux-strip... (cached) mips-openwrt-linux-musl-strip
checking for mips-openwrt-linux-ranlib... mips-openwrt-linux-musl-gcc-ranlib
checking command to parse mips-openwrt-linux-musl-gcc-nm output from mips-openwrt-linux-musl-gcc object... ok
checking for sysroot... no
checking for mips-openwrt-linux-mt... no
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if mips-openwrt-linux-musl-gcc supports -fno-rtti -fno-exceptions... no
checking for mips-openwrt-linux-musl-gcc option to produce PIC... -fPIC -DPIC
checking if mips-openwrt-linux-musl-gcc PIC flag -fPIC -DPIC works... yes
checking if mips-openwrt-linux-musl-gcc static flag -static works... yes
checking if mips-openwrt-linux-musl-gcc supports -c -o file.o... yes
checking if mips-openwrt-linux-musl-gcc supports -c -o file.o... (cached) yes
checking whether the mips-openwrt-linux-musl-gcc linker (mips-openwrt-linux-musl-ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... yes
checking whether a program can dlopen itself... cross
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for mips-openwrt-linux-gcc... (cached) mips-openwrt-linux-musl-gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether mips-openwrt-linux-musl-gcc accepts -g... (cached) yes
checking for mips-openwrt-linux-musl-gcc option to accept ISO C89... (cached) none needed
checking whether mips-openwrt-linux-musl-gcc understands -c and -o together... (cached) yes
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking sys/inotify.h usability... yes
checking sys/inotify.h presence... yes
checking for sys/inotify.h... yes
checking sys/epoll.h usability... yes
checking sys/epoll.h presence... yes
checking for sys/epoll.h... yes
checking sys/event.h usability... no
checking sys/event.h presence... no
checking for sys/event.h... no
checking port.h usability... no
checking port.h presence... no
checking for port.h... no
checking poll.h usability... yes
checking poll.h presence... yes
checking for poll.h... yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/eventfd.h usability... yes
checking sys/eventfd.h presence... yes
checking for sys/eventfd.h... yes
checking sys/signalfd.h usability... yes
checking sys/signalfd.h presence... yes
checking for sys/signalfd.h... yes
checking for inotify_init... yes
checking for epoll_ctl... yes
checking for kqueue... no
checking for port_create... no
checking for poll... yes
checking for select... yes
checking for eventfd... yes
checking for signalfd... yes
checking for clock_gettime... yes
checking for nanosleep... yes
checking for library containing floor... none required
checking for thread local storage (TLS) class... __thread
checking zlib.h usability... no
checking zlib.h presence... no
checking for zlib.h... no
Makefile:109: recipe for target '/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/build_dir/target-mips_34kc_musl-1.1.14/shadowsocks-libev/openssl/shadowsocks-libev-2.4.5/.configured_yyy' failed
make[2]: Leaving directory '/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/package/shadowsocks-libev'
package/Makefile:195: recipe for target 'package/shadowsocks-libev/compile' failed
make[1]: Leaving directory '/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64'
/tmp/OpenWrt-SDK-ar71xx-nand_gcc-5.3.0_musl-1.1.14.Linux-x86_64/include/toplevel.mk:185: recipe for target 'package/shadowsocks-libev/compile' failed

而 zlib1g zlib1g-dev 等都已经安装。
如果记忆可靠的话，在编译 2.4.4 时没有此错误出现，且能够成功编译。

**Comment by aa65535** [comment]
安装对应的软件包在 https://wiki.openwrt.org/doc/howto/buildroot.exigence 里查找。

**Comment by EdiTurn** [comment]
对应的软件包是指 zlib ？已经安装了。如果有导致此问题的其他依赖，请告知一下。

**Comment by EdiTurn** [comment]
已经尝试安装表格中所有软件包，然并无助于解决此问题。

**Comment by EdiTurn** [comment]
@aa65535 我尝试在 DigitalOcean 上开了 CentOS、Debian 来进行编译，也出现相同的错误。

解决方法：在 SDK 根目录中运行
./scripts/feeds update -a
./scripts/feeds install zlib
./scripts/feeds install libopenssl
./scripts/feeds install libpolarssl
然后再进行编译。

**Comment by hitsmaxft** [comment]
更新base部分就足够了  `./scripts/feeds update base`
```
./scripts/feeds install zlib
./scripts/feeds install libopenssl
./scripts/feeds install libpolarssl
``
然后安装依赖

另外 openwrt的编译脚本比较坑人, 依赖 svn (subversion) , 执行失败也不提示, 还是shell 一步一步debug 才找到的

**Comment by vimagick** [comment]
You can edit [package/shadowsocks-libev/Makefile][1], append `+zlib` as dependency.

```diff
- Package/shadowsocks-libev-spec = $(call Package/shadowsocks-libev/Default,openssl,(OpenSSL),+libopenssl +libpthread +ipset +ip)
+ Package/shadowsocks-libev-spec = $(call Package/shadowsocks-libev/Default,openssl,(OpenSSL),+libopenssl +libpthread +ipset +ip +zlib)
```

[1]: https://github.com/shadowsocks/openwrt-shadowsocks/blob/master/Makefile#L42
