### ISSUE TITLE
/etc/rc.common: line 1: server: parameter not set or nul

### ISSUE THREAD

**Issue by fiture** [shadowsocks/openwrt-shadowsocks#240]
http://downloads.openwrt.org.cn/PandoraBox/ralink/packages/base/shadowsocks-libev-spec_2.2.1-1_ralink.ipk.

luci-app-shadowsocks-spec_1.3.8-1_all.ipk

执行：/etc/init.d/shadowsocks start 时，就报错，实在找不出什么原因，帮忙看看啦

```shell
[root@PandoraBox:/root]# /etc/init.d/shadowsocks start
sh: 0: unknown operand
/etc/rc.common: line 1: server: parameter not set or null
```

**Comment by aa65535** [comment]
#147
