### ISSUE TITLE
你好，是否有让 shadowsocks-libev-spec 支持 ipv6 的计划？

### ISSUE THREAD

**Issue by nanxiaobei** [shadowsocks/openwrt-shadowsocks#241]
目前的情况是这样的：

其它墙外网站正常打开，https://www.google.com/ 也正常打开，
但是直接在浏览器地址栏输入 google.com (非 https) 访问，链接会被重置。

OpenWrt 系统日志查看，
访问 Google 时，DNS 返回的 IP 是日本的 ipv6 地址，DNS 结果正确。
但是 google.com (非 https) 会被重置，
https://www.google.com/ 会跳转为香港的 https://www.google.com.hk，

用电脑上的 shadowsocks-windows 代理，
google.com (非 https) 可以打开，
https://www.google.com/  跳转为 https://www.google.co.jp，

应该是 shadowsocks-libev-spec 没有代理 ipv6 ，但 shadowsocks-windows 可以代理 ipv6。
所以 Google 根据我的电信宽带 ipv6 地址最终判断给了香港的 IP，
google.com  (非 https) 链接被重置，电信 ipv6 https Google 可以打开。

综上，可否让 shadowsocks-libev-spec 像 shadowsocks-windows 一样，可以代理 DNS 返回的 ipv6 IP?
虽然不影响 https Google 使用，但还是希望能支持的话更好~ ^_^

**Comment by aa65535** [comment]
no plan for this.
