### ISSUE TITLE
不会自动安装iptables-mod-tproxy

### ISSUE THREAD

**Issue by polong** [shadowsocks/openwrt-shadowsocks#250]
不会自动安装iptables-mod-tproxy

**Comment by aa65535** [comment]
现在不依赖 `iptables-mod-tproxy` 了，没有安装 `iptables-mod-tproxy` 时，将禁用 UDP relay 功能，如果需要启用 UDP relay ，手动安装 `iptables-mod-tproxy` 即可。

参考 #245 , 此变更在 4989d9f3cfa23803cc36420d4ea40de65215cae3
