### ISSUE TITLE
可否添加个国内外分流模式?

### ISSUE THREAD

**Issue by Aar0nJaw** [shadowsocks/openwrt-shadowsocks#252]
可否添加个分流, 这样全局模式的话有些不方便
而且在luci界面点击"保存并应用"设置无效 , 必须手动/etc/init.d/shadowsocks restart才会生效

**Comment by lixingcong** [comment]
spec版有

**Comment by Aar0nJaw** [comment]
请问“spec版”在哪 我没有找到@lixingcong
