### ISSUE TITLE
请问怎么让shadowsocks监听1080并非全局模式

### ISSUE THREAD

**Issue by voti** [shadowsocks/openwrt-shadowsocks#253]
我用的是openwrt优化版
我想仅仅开启shadowsocks
然后通过pac分发给127.0.0.1#1080
但是不知道怎么单独开启

**Comment by voti** [comment]
ssh 192.168.1.1
$ /etc/init.d/shadowsocks start
好像这样并没有用。不知道该如何配置/etc/config/shadowsocks

**Comment by cokebar** [comment]
use shadowsocks-libev, do not use shadowsocks-libev-spec.

**Comment by tlze** [comment]
安装shadowsocks-libev版本，
编辑/etc/shadowsocks.json
$ /etc/init.d/shadowsocks start

**Comment by voti** [comment]
谢谢2位的提议
