### ISSUE TITLE
代理正常 但是google twitter facebook等都打不开

### ISSUE THREAD

**Issue by zxcwdta** [shadowsocks/openwrt-shadowsocks#255]
游戏都能走代理，但是标题上面所说的网站都打不开，开全局代理都不行。openWrt 14.07 shadowsocks-libev-spec  2.4.6-1。自己编译了几个版本都是这样

**Comment by zxcwdta** [comment]
问题已解决 DNS污染的问题 强制安装了tproxy使用udp转发就没问题了

**Comment by gnu4cn** [comment]
可以说得具体点儿吗，我遇到了相同的问题。

**Comment by zxcwdta** [comment]
打开UDP转发，设置端口 然后在CHINADNS里面填入SS的UDP数据，最后在DNS里面填入CHINADNS的端口。

**Comment by gnu4cn** [comment]
谢谢
