### ISSUE TITLE
luci界面滚动条的问题

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/openwrt-shadowsocks#262]
在openwrt的luci后台，打开`服务 --> Shadowsocks`，滚动条会自动跳到中间

![1](https://cloud.githubusercontent.com/assets/4590439/15799772/edcdd7fc-2a99-11e6-94c7-f50d11765ba3.png)

**Comment by lixingcong** [comment]
实测该问题可以reproduce

**Comment by pexcn** [comment]
@lixingcong 这个问题我从上一年开始用到现在，一直存在...

**Comment by aa65535** [comment]
这个是 luci 的问题，页面太高都这样。

**Comment by pexcn** [comment]
但`系统 --> 启动项`之类的系统页面没有问题

**Comment by pexcn** [comment]
这个问题会不会是内容先加载出来了再去加载`css` ?
