### ISSUE TITLE
 无法编译ss for EA4500

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/openwrt-shadowsocks#265]
我把EA4500刷成openwrt trunk（Designated Driver），我想自己编译最新的ss，每次都提示zlib.h不存在，但是这个文件在/usr/include，这个路径我也加入PATH了，能不能发布一个适合的ipk版本呢？
我下载的SDK地址如下：https://downloads.openwrt.org/snapshots/trunk/kirkwood/generic/OpenWrt-SDK-kirkwood_gcc-5.3.0_musl-1.1.14_eabi.Linux-x86_64.tar.bz2

**Comment by aa65535** [comment]
SDK的问题，可以自己编译 zlib
这里使用的 zlib 是 openwrt 平台下的，可以换 15.05 的SDK试试。
