### ISSUE TITLE
优酷土豆播放某些视频的时候提示“仅限中国大陆地区播放“

### ISSUE THREAD

**Issue by 467815891a** [shadowsocks/openwrt-shadowsocks#271]
提示：抱歉，改视频仅限中国大陆地区播放，请您观看其他视频。
关闭SS后正常，用的是默认的ChinaDNS路由表,DNS解析是ChinaDNS,也是默认的国内路由表,上游服务器114.114.114.114,8.8.8.8,119.29.29.29,208.67.222.220

**Comment by heyggu** [comment]
在全局模式下，一种办法，可以把这些网站用Unblock-Youku项目的DNS解析。

**Comment by 467815891a** [comment]
@heyggu 照你讲的，优酷单独解析就好了，3Q！
