### ISSUE TITLE
是否可能针对redsocks实现ss-rules？

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/openwrt-shadowsocks#272]
如此即可将Shadowsocks建于内网高性能NAS上，无需较强的路由器性能即可工作。

**Comment by aa65535** [comment]
可以将「内网高性能NAS」作为网关. 
性能瓶颈在 NAT.

**Comment by t123yh** [comment]
路由器解密 AES 速度有限。我在本地的 Shadowsocks 服务器速度能到 7 MB/s，而路由器只有 2 MB/s。
