### ISSUE TITLE
每次启动路由器，SS服务是运行状态，但是UDP转发是未运行状态

### ISSUE THREAD

**Issue by pop4ever** [shadowsocks/openwrt-shadowsocks#276]
我需要到启动项里面，手动重启SS服务后，UDP转发才会显示运行状态，SS也能用了。

如何才能每次路由器启动的时候默认就启动UDP转发？

确认我已经在SS LUCI配置里勾选了UDP转发。

安装了最新的SS-libev-spec，chinadns以及对应的luci-app。

谢谢

**Comment by chnt7305** [comment]
装 pdnsd 转发 udp 到 tcp 好了。

**Comment by aa65535** [comment]
到系统日志里看一下 ss-tunnel 相关的日志信息

**Comment by pop4ever** [comment]
先close吧，这两天重启路由器发现好了，也不知道是啥原因。
