### ISSUE TITLE
能否告知全局设置中的UDP服务器有什么作用？

### ISSUE THREAD

**Issue by lingbaoboy** [shadowsocks/openwrt-shadowsocks#278]
能否告知**全局设置**中的**UDP服务器**有什么作用？
和**UDP转发**有什么关系？
我原来一直以为开启UDP转发后必须打开UDP服务器才有作用，但是现在看来不是。

**Comment by pexcn** [comment]
我也想问...

**Comment by aa65535** [comment]
**全局设置**中的 **UDP 服务器**是作为所有 UDP 相关请求的服务器。
如果选择停用则 **UDP 转发**使用的服务器就是**全局服务器**，此时只启动一个 ss-redir 进程并只代理 TCP 协议的请求。
如果选择启用（选择**与全局服务器相同**或者其他可用服务器）则 **UDP 转发**使用的服务器就是**UDP 服务器**，此时启动两个ss-redir 进程，使用**全局服务器**的进程代理 TCP，使用**UDP 服务器**的进程代理 UDP。
注：**UDP 转发**使用的是 ss-tunnel，不同与开启了 UDP 个  ss-redir。

**Comment by cokebar** [comment]
@aa65535 "UDP转发"是不是改成“端口转发”之类的更为精确不易混淆，如果我没有搞错，那么ss-tunnel并不一定转发UDP，TCP也是可以的。
“UDP服务器”则比较明确，用来代理UDP流量的
