### ISSUE TITLE
服务无法正常运行

### ISSUE THREAD

**Issue by rainywinter** [shadowsocks/openwrt-shadowsocks#279]
NETGEAR WNDR3700v4    openwrt-15.05.1-ar71xx-nand-wndr3700v4-squashfs-sysupgrade  shadowsocks-libev-spec_2.4.8-1_ar71xx.ipk
路由器可以正常访问网络，在openwrt上执行 /etc/init.d/shadowsocks start命令后，没有相关 ss-redir ss-rules 进程启动，也没有报错。手动执行 ss-local shadowsocks.json 命令 ，打开浏览器访问Google，控制台没有收到任何数据，没有日志。
如果安装shadowsocks-libev_2.4.8-1_ar71xx.ipk这个版本 可以正常启动，进程也存在，但是无法翻墙，ss服务器也收不到任何数据，（配置是正常的，使用shadowsocks-for-win可以正常翻墙）。
请教该如何解决，谢谢。

**Comment by mrken2004** [comment]
我也发现这个问题。2.48-2版本无法翻墙，在android 6.0.1（Nexus 6p）上wifi链接始终显示叹号，之前的版本正常。

**Comment by aa65535** [comment]
查看系统日志
