### ISSUE TITLE
shadowsocks-libev-spec 2.4.8-2  luci无法找到

### ISSUE THREAD

**Issue by levelwithme** [shadowsocks/openwrt-shadowsocks#284]
openwrt BB 14.07 
shadowsocks-libev-spec 2.4.8-2 和  luci-app-shadowsocks-spec 1.5.0-1编译进固件
进入界面后选shadowscoks
提示：shadowsocks-libev-spec not found

**Comment by aa65535** [comment]
shadowsocks-libev-spec 有在软件包列表中吗？

**Comment by levelwithme** [comment]
opkg search *shadowsocks-libev* 看到是有shadowsocks-libev-spec 和 luci-shadowsocks。
同样的文件配置。在CC15.5.1没有问题。不知道是不是个例。

**Comment by aa65535** [comment]
确认是否在已安装列表中有 shadowsocks-libev-spec* 这个软件包。没有的话，安装一下。

**Comment by levelwithme** [comment]
编译了CC 15.5.1  shadowsocks-libev-spec 2.4.8-8816fa1 折腾了两天还没法工作。抽空帮看看那里出了问题吧。
 
iptables-save -t nat 

结果:

root@Openwrt:~# iptables-save -t nat
# Generated by iptables-save v1.4.21 on Tue Aug  9 08:21:11 2016
*nat
:PREROUTING ACCEPT [1:40]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:SS_SPEC_LAN_AC - [0:0]
:SS_SPEC_WAN_AC - [0:0]
:SS_SPEC_WAN_FW - [0:0]
:adb-nat - [0:0]
:delegate_postrouting - [0:0]
:delegate_prerouting - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -i br-lan -p tcp -j SS_SPEC_LAN_AC
-A PREROUTING -j delegate_prerouting
-A OUTPUT -p tcp -j SS_SPEC_WAN_AC
-A POSTROUTING -j delegate_postrouting
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_lan_bp src -j RETURN
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_lan_fw src -j SS_SPEC_WAN_FW
-A SS_SPEC_LAN_AC -m set --match-set ss_spec_lan_no src -j SS_SPEC_WAN_AC
-A SS_SPEC_LAN_AC -j SS_SPEC_WAN_AC
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_fw dst -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_AC -m set --match-set ss_spec_wan_bp dst -j RETURN
-A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
-A SS_SPEC_WAN_FW -m set --match-set ss_spec_wan_sp dst -j RETURN
-A SS_SPEC_WAN_FW -p tcp -j REDIRECT --to-ports 1080
-A adb-nat -p tcp -m comment --comment adb-nat -m tcp --dport 80 -j DNAT --to-destination 192.168.1.1:65534
-A adb-nat -p tcp -m comment --comment adb-nat -m tcp --dport 443 -j DNAT --to-destination 192.168.1.1:65535
-A adb-nat -m comment --comment adb-nat -j RETURN
-A delegate_postrouting -m comment --comment "user chain for postrouting" -j postrouting_rule
-A delegate_postrouting -o br-lan -j zone_lan_postrouting
-A delegate_postrouting -o pppoe-wan -j zone_wan_postrouting
-A delegate_postrouting -o eth0 -j zone_wan_postrouting
-A delegate_prerouting -m comment --comment "user chain for prerouting" -j prerouting_rule
-A delegate_prerouting -i br-lan -j zone_lan_prerouting
-A delegate_prerouting -i pppoe-wan -j zone_wan_prerouting
-A delegate_prerouting -i eth0 -j zone_wan_prerouting
-A prerouting_rule -i br-lan -p udp -m comment --comment adb-dns -m udp --dport 53 -j DNAT --to-destination 192.168.1.1:53
-A prerouting_rule -i br-lan -p tcp -m comment --comment adb-dns -m tcp --dport 53 -j DNAT --to-destination 192.168.1.1:53
-A prerouting_rule -d 198.18.0.1/32 -m comment --comment adb-nat -j adb-nat
-A zone_lan_postrouting -m comment --comment "user chain for postrouting" -j postrouting_lan_rule
-A zone_lan_prerouting -m comment --comment "user chain for prerouting" -j prerouting_lan_rule
-A zone_wan_postrouting -m comment --comment "user chain for postrouting" -j postrouting_wan_rule
-A zone_wan_postrouting -j MASQUERADE
-A zone_wan_prerouting -m comment --comment "user chain for prerouting" -j prerouting_wan_rule
COMMIT
# Completed on Tue Aug  9 08:21:11 2016


ps 

 1505 root       836 S    /usr/bin/chinadns -p 5353 -s 114.114.114.114,8.8.4.4 -c /etc/chinadns_chn
 1596 root       800 S    odhcp6c -s /lib/netifd/dhcpv6.script -P0 -t120 pppoe-wan
 1702 nobody    2004 S    /usr/sbin/dnsmasq -C /var/etc/dnsmasq.conf -k -x /var/run/dnsmasq/dnsmasq
 1758 root      1364 S    /usr/sbin/ntpd -n -S /usr/sbin/ntpd-hotplug -p 0.openwrt.pool.ntp.org -p
 2001 root      1376 S    /usr/sbin/uhttpd -h /www/adblock -N 25 -T 1 -r adbIPv4_80 -k 0 -t 0 -R -D
 2003 root      1376 S    /usr/sbin/uhttpd -h /www/adblock -N 25 -T 0 -r adbIPv4_443 -k 0 -t 0 -R -
 2824 root      1220 S    /usr/sbin/dropbear -F -P /var/run/dropbear.1.pid -p 22 -K 300
 2825 root      1368 S    -ash
 3326 root      2888 S    /usr/bin/ss-redir -c /var/etc/shadowsocks.json -A -f /var/run/ss-redir.pi
 3362 root      1360 R    ps



root@Openwrt:~# ipset save ss_spec_lan_bp
create ss_spec_lan_bp hash:net family inet hashsize 64 maxelem 65536

add ss_spec_lan_bp 192.168.1.102
root@Openwrt:~# ipset save ss_spec_lan_fw
create ss_spec_lan_fw hash:net family inet hashsize 64 maxelem 65536

root@Openwrt:~# ipset save ss_spec_lan_no
create ss_spec_lan_no hash:net family inet hashsize 64 maxelem 65536


![1](https://cloud.githubusercontent.com/assets/20843810/17510110/19a5fa46-5e50-11e6-9e17-7f7d1be44035.jpg)
![2](https://cloud.githubusercontent.com/assets/20843810/17510123/2d824268-5e50-11e6-9d6d-1f31f19754b0.jpg)
![3](https://cloud.githubusercontent.com/assets/20843810/17510149/44c7530a-5e50-11e6-8e03-6fa5ab696add.jpg)
![4](https://cloud.githubusercontent.com/assets/20843810/17510165/51367792-5e50-11e6-9ba7-4af2d4dcb5d0.jpg)

**Comment by aa65535** [comment]
`iptables-mod-tproxy` 可以在 make menuconfig 里找到, 如果用的是 ImageBuilder , 可以去 https://downloads.openwrt.org/ 下载 `iptables-mod-tproxy`  的 ipk 文件以及依赖包的 ipk, 大概是以下几个, 放到 packages 的对应目录下.
```
iptables-mod-tproxy
kmod-ipt-tproxy
kmod-ipt-conntrack
kmod-ipv6
kmod-ip6tables
kmod-ipt-core
```

关于不工作, 与 #288 类似（iptables规则没问题）, 请检查一下服务器配置（服务器是否支持一次认证）
另外对于 `192.168.1.102` 这个 IP ss 是“不工作的”

**Comment by Randy000** [comment]
请注意隐藏你的服务器IP信息，建议打码处理。@levelwithme
