### ISSUE TITLE
iptables: Too many links.

### ISSUE THREAD

**Issue by myliyifei** [shadowsocks/openwrt-shadowsocks#29]
/etc/init.d/shadowsocks stop或者start的时候提示

iptables: Too many links.

**Comment by myliyifei** [comment]
root@Gargoyle:/etc/shadowsocks# uci export shadowsocks
package shadowsocks

config shadowsocks
        option enable '1'
        option use_conf_file '1'
        option config_file '/etc/shadowsocks/config.json'
        option ignore_list '/etc/shadowsocks/ignore.list'
        option tunnel_enable '1'
        option tunnel_port '5353'
        option tunnel_forward '8.8.4.4:53'
        option lan_ac_mode '0'



root@Gargoyle:/etc/shadowsocks# iptables-save -t nat
# Generated by iptables-save v1.4.10 on Thu Jan  1 23:46:23 2015
*nat
:PREROUTING ACCEPT [36:2227]
:INPUT ACCEPT [4:337]
:OUTPUT ACCEPT [15:1317]
:POSTROUTING ACCEPT [15:1317]
:MINIUPNPD - [0:0]
:SS_SPEC_LAN_AC - [0:0]
:SS_SPEC_WAN_AC - [0:0]
:delegate_postrouting - [0:0]
:delegate_prerouting - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -j delegate_prerouting 
-A OUTPUT -p tcp -j SS_SPEC_WAN_AC 
-A POSTROUTING -j delegate_postrouting 
-A delegate_postrouting -m comment --comment "user chain for postrouting" -j postrouting_rule 
-A delegate_postrouting -o br-lan -j zone_lan_postrouting 
-A delegate_postrouting -o pppoe-wan -j zone_wan_postrouting 
-A delegate_prerouting -m comment --comment "user chain for prerouting" -j prerouting_rule 
-A delegate_prerouting -i br-lan -j zone_lan_prerouting 
-A delegate_prerouting -i pppoe-wan -j zone_wan_prerouting 
-A postrouting_rule -o eth0.2 -j MASQUERADE 
-A zone_lan_postrouting -m comment --comment "user chain for postrouting" -j postrouting_lan_rule 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p tcp -m tcp --dport 3389 -m comment --comment "RDP (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p udp -m udp --dport 3389 -m comment --comment "RDP (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p tcp -m tcp --dport 4172 -m comment --comment "PcoIP (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p udp -m udp --dport 4172 -m comment --comment "PcoIP (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p tcp -m tcp --dport 11443 -m comment --comment "PcoIP agent (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_prerouting -m comment --comment "user chain for prerouting" -j prerouting_lan_rule 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p tcp -m tcp --dport 13389 -m comment --comment "RDP (reflection)" -j DNAT --to-destination 192.168.3.165:3389 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p udp -m udp --dport 13389 -m comment --comment "RDP (reflection)" -j DNAT --to-destination 192.168.3.165:3389 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p tcp -m tcp --dport 14172 -m comment --comment "PcoIP (reflection)" -j DNAT --to-destination 192.168.3.165:4172 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p udp -m udp --dport 14172 -m comment --comment "PcoIP (reflection)" -j DNAT --to-destination 192.168.3.165:4172 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p tcp -m tcp --dport 11443 -m comment --comment "PcoIP agent (reflection)" -j DNAT --to-destination 192.168.3.165:11443 
-A zone_lan_prerouting -p tcp -j SS_SPEC_LAN_AC 
-A zone_wan_postrouting -m comment --comment "user chain for postrouting" -j postrouting_wan_rule 
-A zone_wan_postrouting -j MASQUERADE 
-A zone_wan_prerouting -j MINIUPNPD 
-A zone_wan_prerouting -p tcp -m tcp --dport 8422 -j CONNMARK --set-xmark 0x80/0x80 
-A zone_wan_prerouting -p tcp -m tcp --dport 8422 -j REDIRECT --to-ports 22 
-A zone_wan_prerouting -p tcp -m tcp --dport 8443 -j CONNMARK --set-xmark 0x80/0x80 
-A zone_wan_prerouting -p tcp -m tcp --dport 8443 -j REDIRECT --to-ports 443 
-A zone_wan_prerouting -m comment --comment "user chain for prerouting" -j prerouting_wan_rule 
-A zone_wan_prerouting -p tcp -m tcp --dport 13389 -m comment --comment "RDP" -j DNAT --to-destination 192.168.3.165:3389 
-A zone_wan_prerouting -p udp -m udp --dport 13389 -m comment --comment "RDP" -j DNAT --to-destination 192.168.3.165:3389 
-A zone_wan_prerouting -p tcp -m tcp --dport 14172 -m comment --comment "PcoIP" -j DNAT --to-destination 192.168.3.165:4172 
-A zone_wan_prerouting -p udp -m udp --dport 14172 -m comment --comment "PcoIP" -j DNAT --to-destination 192.168.3.165:4172 
-A zone_wan_prerouting -p tcp -m tcp --dport 11443 -m comment --comment "PcoIP agent" -j DNAT --to-destination 192.168.3.165:11443 
COMMIT
# Completed on Thu Jan  1 23:46:23 2015

**Comment by myliyifei** [comment]
root@Gargoyle:/etc/shadowsocks# /etc/init.d/shadowsocks start
iptables: Too many links.
iptables: Too many links.
root@Gargoyle:/etc/shadowsocks# iptables-save -t nat
# Generated by iptables-save v1.4.10 on Thu Jan  1 23:51:31 2015
*nat
:PREROUTING ACCEPT [3:387]
:INPUT ACCEPT [3:333]
:OUTPUT ACCEPT [2:120]
:POSTROUTING ACCEPT [0:0]
:MINIUPNPD - [0:0]
:SS_SPEC_LAN_AC - [0:0]
:SS_SPEC_WAN_AC - [0:0]
:delegate_postrouting - [0:0]
:delegate_prerouting - [0:0]
:postrouting_lan_rule - [0:0]
:postrouting_rule - [0:0]
:postrouting_wan_rule - [0:0]
:prerouting_lan_rule - [0:0]
:prerouting_rule - [0:0]
:prerouting_wan_rule - [0:0]
:zone_lan_postrouting - [0:0]
:zone_lan_prerouting - [0:0]
:zone_wan_postrouting - [0:0]
:zone_wan_prerouting - [0:0]
-A PREROUTING -j delegate_prerouting 
-A OUTPUT -p tcp -j SS_SPEC_WAN_AC 
-A OUTPUT -p tcp -j SS_SPEC_WAN_AC 
-A POSTROUTING -j delegate_postrouting 
-A SS_SPEC_LAN_AC -p tcp -j SS_SPEC_WAN_AC 
-A SS_SPEC_WAN_AC -p tcp -m set --match-set shadowsocks dst -j RETURN 
-A SS_SPEC_WAN_AC -p tcp -j REDIRECT --to-ports 1080 
-A delegate_postrouting -m comment --comment "user chain for postrouting" -j postrouting_rule 
-A delegate_postrouting -o br-lan -j zone_lan_postrouting 
-A delegate_postrouting -o pppoe-wan -j zone_wan_postrouting 
-A delegate_prerouting -m comment --comment "user chain for prerouting" -j prerouting_rule 
-A delegate_prerouting -i br-lan -j zone_lan_prerouting 
-A delegate_prerouting -i pppoe-wan -j zone_wan_prerouting 
-A postrouting_rule -o eth0.2 -j MASQUERADE 
-A zone_lan_postrouting -m comment --comment "user chain for postrouting" -j postrouting_lan_rule 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p tcp -m tcp --dport 3389 -m comment --comment "RDP (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p udp -m udp --dport 3389 -m comment --comment "RDP (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p tcp -m tcp --dport 4172 -m comment --comment "PcoIP (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p udp -m udp --dport 4172 -m comment --comment "PcoIP (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_postrouting -s 192.168.3.0/24 -d 192.168.3.165/32 -p tcp -m tcp --dport 11443 -m comment --comment "PcoIP agent (reflection)" -j SNAT --to-source 192.168.3.1 
-A zone_lan_prerouting -m comment --comment "user chain for prerouting" -j prerouting_lan_rule 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p tcp -m tcp --dport 13389 -m comment --comment "RDP (reflection)" -j DNAT --to-destination 192.168.3.165:3389 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p udp -m udp --dport 13389 -m comment --comment "RDP (reflection)" -j DNAT --to-destination 192.168.3.165:3389 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p tcp -m tcp --dport 14172 -m comment --comment "PcoIP (reflection)" -j DNAT --to-destination 192.168.3.165:4172 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p udp -m udp --dport 14172 -m comment --comment "PcoIP (reflection)" -j DNAT --to-destination 192.168.3.165:4172 
-A zone_lan_prerouting -s 192.168.3.0/24 -d 27.16.229.92/32 -p tcp -m tcp --dport 11443 -m comment --comment "PcoIP agent (reflection)" -j DNAT --to-destination 192.168.3.165:11443 
-A zone_lan_prerouting -p tcp -j SS_SPEC_LAN_AC 
-A zone_lan_prerouting -p tcp -j SS_SPEC_LAN_AC 
-A zone_wan_postrouting -m comment --comment "user chain for postrouting" -j postrouting_wan_rule 
-A zone_wan_postrouting -j MASQUERADE 
-A zone_wan_prerouting -j MINIUPNPD 
-A zone_wan_prerouting -p tcp -m tcp --dport 8422 -j CONNMARK --set-xmark 0x80/0x80 
-A zone_wan_prerouting -p tcp -m tcp --dport 8422 -j REDIRECT --to-ports 22 
-A zone_wan_prerouting -p tcp -m tcp --dport 8443 -j CONNMARK --set-xmark 0x80/0x80 
-A zone_wan_prerouting -p tcp -m tcp --dport 8443 -j REDIRECT --to-ports 443 
-A zone_wan_prerouting -m comment --comment "user chain for prerouting" -j prerouting_wan_rule 
-A zone_wan_prerouting -p tcp -m tcp --dport 13389 -m comment --comment "RDP" -j DNAT --to-destination 192.168.3.165:3389 
-A zone_wan_prerouting -p udp -m udp --dport 13389 -m comment --comment "RDP" -j DNAT --to-destination 192.168.3.165:3389 
-A zone_wan_prerouting -p tcp -m tcp --dport 14172 -m comment --comment "PcoIP" -j DNAT --to-destination 192.168.3.165:4172 
-A zone_wan_prerouting -p udp -m udp --dport 14172 -m comment --comment "PcoIP" -j DNAT --to-destination 192.168.3.165:4172 
-A zone_wan_prerouting -p tcp -m tcp --dport 11443 -m comment --comment "PcoIP agent" -j DNAT --to-destination 192.168.3.165:11443 
COMMIT
# Completed on Thu Jan  1 23:51:31 2015

**Comment by aa65535** [comment]
`iptables-save` 导出的规则每行后面都与一个空格的缘故。
