### ISSUE TITLE
能否在 shadowsocks-libev-spec 添加  SOCKS5 代理功能。

### ISSUE THREAD

**Issue by liumailong** [shadowsocks/openwrt-shadowsocks#30]
有时候不想使用透明代理，能否增加切换SOCKS5 代理模式的功能。

**Comment by aa65535** [comment]
Duplicated to #26

**Comment by liumailong** [comment]
我用的是X86 版，空间完全够。
会来翻墙的路由，那怕只有16M的空间，也不差这几百K

**Comment by aa65535** [comment]
spec 版方案用不到 ss-local，所以不会去集成它。

如果空间足够可以额外安装 shadowsocks-libev .或者修改 [此处](https://github.com/shadowsocks/openwrt-shadowsocks/blob/18a5d49/Makefile#L97) 然后自己编译。

至于切换到 SOCKS 代理的功能，目前没有做出这种大而全的方案的打算。
