### ISSUE TITLE
LEDE X86_64环境下编译失败

### ISSUE THREAD

**Issue by xseven007** [shadowsocks/openwrt-shadowsocks#302]
openssl的可以正常编译
但是mbedtls的却编译失败，出现以下错误日志
checking for library containing floor... none required
checking for thread local storage (TLS) class... __thread
checking for mbedtls_cipher_setup in -lmbedcrypto... yes
checking whether mbedtls supports Cipher Feedback mode or not... configure: error: MBEDTLS_CIPHER_MODE_CFB required
Makefile:83: recipe for target '/opt/lede-2/build_dir/target-x86_64_musl-1.1.15/shadowsocks-libev/mbedtls/shadowsocks-libev-2.5.5/.configured_yyynnnn' failed
make[3]: *** [/opt/lede-2/build_dir/target-x86_64_musl-1.1.15/shadowsocks-libev/mbedtls/shadowsocks-libev-2.5.5/.configured_yyynnnn] Error 1
make[3]: Leaving directory '/opt/lede-2/package/shadowsocks-libev'
package/Makefile:127: recipe for target 'package/shadowsocks-libev/compile' failed
make[2]: *** [package/shadowsocks-libev/compile] Error 2
make[2]: Leaving directory '/opt/lede-2'
package/Makefile:124: recipe for target '/opt/lede-2/staging_dir/target-x86_64_musl-1.1.15/stamp/.package_compile' failed
make[1]: *** [/opt/lede-2/staging_dir/target-x86_64_musl-1.1.15/stamp/.package_compile] Error 2
make[1]: Leaving directory '/opt/lede-2'
/opt/lede-2/include/toplevel.mk:193: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by aa65535** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/877#issuecomment-252825710
