### ISSUE TITLE
mw4530r, openwrt15.05.1版本，不支持UDP relay server

### ISSUE THREAD

**Issue by shihhuangti** [shadowsocks/openwrt-shadowsocks#303]
tproxy的两个包都安装了。是iptables-mod-tproxy, 
和kmod-ipt-tproxy。

但是还是显示：unusable-missing iptables-mod-tproxy or ip.

**Comment by aa65535** [comment]
```
opkg update
opkg install ip
```

**Comment by shihhuangti** [comment]
按照你提供的方式，果然可以了。多谢。

不过安装ip的时候，提示冲突，和ioroute2的某个配置文件冲突。不知道是不是问题，有无影响？
