### ISSUE TITLE
编译中错误configure: error: Cannot find pcre library. Configure --with-pcre=DIR

### ISSUE THREAD

**Issue by arainzhao** [shadowsocks/openwrt-shadowsocks#306]
Ubuntu 14.04 LTS CC 15.05.1编译2.5.6版本时候出现错误
checking for dlopen... yes
checking whether a program can dlopen itself... cross
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for pcre-config... pcre-config
checking for pcre headers in ... not found
checking for library containing pcre_exec... no
configure: error: Cannot find pcre library. Configure --with-pcre=DIR
make[2]: *** [/home/arainzhao/lede/source/build_dir/target-mips_24kc_musl-1.1.15/shadowsocks-libev/openssl/shadowsocks-libev-2.5.6/.configured_yyy] Error 1
make[2]: Leaving directory `/home/arainzhao/lede/source/package/shadowsocks-libev'
make[1]: *** [package/shadowsocks-libev/compile] Error 2
make[1]: Leaving directory `/home/arainzhao/lede/source'
make: *** [package/shadowsocks-libev/compile] 错误 2
arainzhao@arainzhao-virtual-machine:~/lede/source$ 
请问该如何处理，谢谢！

**Comment by aa65535** [comment]
```sh
./scripts/feeds update packages
./scripts/feeds install libpcre
```
