### ISSUE TITLE
能否考虑发布用libreSSL编译的二进制包

### ISSUE THREAD

**Issue by s7lx** [shadowsocks/openwrt-shadowsocks#314]
既能和openssl一样支持所有加密算法，又能减少体积。而且由于是静态链接，因此也摆脱了对openwrt-openssl的依赖

**Comment by s7lx** [comment]
这也用`redirect` ? libressl完全兼容openssl，代码都不改，直接强制指向一下openssl的目录，编译就能过了。绝对属于编译的问题而非ss-libev自身的问题

**Comment by wongsyrone** [comment]
在openwrt上默认的包是libopenssl，加另外一个暂时看不到提升，除非有明确的测试结果。
