### ISSUE TITLE
English?

### ISSUE THREAD

**Issue by Milewski** [shadowsocks/openwrt-shadowsocks#318]
any guide in english?

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks/wiki

**Comment by Milewski** [comment]
which redirects me back to here... [https://github.com/shadowsocks/shadowsocks/wiki/Ports-and-Clients#openwrt](https://github.com/shadowsocks/shadowsocks/wiki/Ports-and-Clients#openwrt)

**Comment by aa65535** [comment]
You may need [luci-app-shadowsocks](https://github.com/shadowsocks/luci-app-shadowsocks)
