### ISSUE TITLE
小米路由器R1D，

### ISSUE THREAD

**Issue by liliass** [shadowsocks/openwrt-shadowsocks#319]
家里50Mbps带宽， 用小米路由器SS 只能跑30-40Mpbs，CPU usage 就100% 了。   电脑／手机挂SS （路由器SS关了）就可以跑满速。

手机／电脑上SS， CPU usage 才20%-30%。 

我需要更好的路由器吧 ？

**Comment by aa65535** [comment]
路由器性能有限。
