### ISSUE TITLE
3.0为何取消openssl的支持？

### ISSUE THREAD

**Issue by wukaisky** [shadowsocks/openwrt-shadowsocks#320]
LEDE有很多库依赖libopenssl，现在3.0的shadowsocks只支持mbedtls，路由器就只得同时安装libopenssl和libmbedtls，浪费了一百多KB空间。

**Comment by wongsyrone** [comment]
如果你能给新AEAD加上openssl支持，可以在加回来。

**Comment by DreamSeason** [comment]
一百多M空间？ 路由器很少有那么大的可用空间把

**Comment by wukaisky** [comment]
说错了，是一百多KB

**Comment by yy0c** [comment]
Well, this is a shame. OpenSSL is the only library has MIPS assembly optimization, which is very helpful offload these underpowered CPUs inside Wi-Fi routers.
