### ISSUE TITLE
ss-redir load error

### ISSUE THREAD

**Issue by flower-dog3** [shadowsocks/openwrt-shadowsocks#321]
ss-redir: can't load library 'libsodium.so.18'
maybe it needs a soft link.

**Comment by cokebar** [comment]
请到aa65535提供的预编译ipk网址里下载便宜好的libsodium和libmbedtls安装

**Comment by edison0354** [comment]
https://dl.bintray.com/aa65535/opkg/shadowsocks-libev/3.0.0/OpenWrt/ar71xx/
openwrt官方的libsodium似乎比较旧了，这里有新版下载，请根据自己设备的架构选择下载……然后手动装下就好了

**Comment by cokebar** [comment]
LEDE应该都是新版本，LEDE rc1也发布了，正式版也会在本月发布，不如一口气升到LEDE

**Comment by flower-dog3** [comment]
when my jobs down,but /etc/init.d/shadowsocks restart is boot failure,

2017-02-03 15:45 GMT+08:00 Cokebar Chi <notifications@github.com>:

**Comment by flower-dog3** [comment]
cancel OTA is right
