### ISSUE TITLE
3.0.0的udp转发似乎有问题？

### ISSUE THREAD

**Issue by edison0354** [shadowsocks/openwrt-shadowsocks#322]
我路由器上这样给WiiU设的转发规则
iptables -t mangle -A PREROUTING -m mac --mac-source XX:XX:XX:XX:XX:XX -p udp -j TPROXY --on-port 1090 --tproxy-mark 0x01/0x01
iptables -t nat -A PREROUTING -m mac --mac-source XX:XX:XX:XX:XX:XX -p tcp -j REDIRECT --to-port 1090
1090端口是ss-redir的
之前用着没有问题，今儿升到3.0.0之后无论如何也连不上游戏，但是tcp似乎是没有问题的，用privoxy转发的ss-local看网页也没有问题。换过无数个ss服务器测试都这样
折腾了一个多小时，最后退回2.6.2就没有任何问题了……所以怀疑是3.0.0的udp的问题？

**Comment by pexcn** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1154

**Comment by DreamSeason** [comment]
同楼主，今天回家升级了一下。也是折腾了半天，发现了这个问题。3.0的UDP转发有问题，导致DNS解析出问题

**Comment by madeye** [comment]
Try 7ef88b1.
