### ISSUE TITLE
 libmbedtls 

### ISSUE THREAD

**Issue by kk347036700** [shadowsocks/openwrt-shadowsocks#328]
安装出错帮忙看看。wndr 4300 v1版本。已经更新过opkg

root@OpenWrt:/tmp# opkg install shadowsocks-libev_3.0.0-1_ar71xx.ipk 
Installing shadowsocks-libev (3.0.0-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev:
 *      libmbedtls * 
 * opkg_install_cmd: Cannot install package shadowsocks-libev.

**Comment by wanxj119** [comment]
http://openwrt-dist.sourceforge.net/packages/OpenWrt/base/ar71xx/
libmbedtls_2.4.0-2_ar71xx.ipk
opkg install libmbedtls_2.4.0-2_ar71xx.ipk
