### ISSUE TITLE
问一下作者你是如何生成多个平台的ipk的

### ISSUE THREAD

**Issue by cokebar** [shadowsocks/openwrt-shadowsocks#333]
是否是自动化编译？ 求助方法。谢谢！

**Comment by debiansid** [comment]
肯定是

**Comment by cokebar** [comment]
@debiansid 所以我就来问方法了啊^v^. Travis CI之类的可以么。

**Comment by debiansid** [comment]
现在都用lede吧

**Comment by cokebar** [comment]
@debiansid 我指的是不同cpu平台

**Comment by simonsmh** [comment]
使用不同sdk可以实现，但是感觉太麻烦了。
我尝试实现了一下自动化编译：
https://github.com/simonsmh/openwrt-dist

**Comment by cokebar** [comment]
@simonsmh 我也用travis CI试了一下，CC版本可以了， LEDE还没试。

**Comment by aa65535** [comment]
使用 shell 操作不同的 SDK 编译.
