### ISSUE TITLE
ss-redir进程残留

### ISSUE THREAD

**Issue by Mattosx** [shadowsocks/openwrt-shadowsocks#338]
/etc/init.d/shadowsocks 每次重新运行，原来的进程都会残留，可以通过ps看到

**Comment by aa65535** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues

**Comment by aa65535** [comment]
fix via https://github.com/shadowsocks/luci-app-shadowsocks/commit/2054ecd63fddf5e3dd7070592ca1ea6589a76a5a
