### ISSUE TITLE
resolveip，已解决，请关闭

### ISSUE THREAD

**Issue by lwd2136** [shadowsocks/openwrt-shadowsocks#34]
Installing shadowsocks-libev-spec (2.0.4-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev-spec:
 *      resolveip *
 * opkg_install_cmd: Cannot install package shadowsocks-libev-spec.

已解决，请关闭吧

**Comment by lwd2136** [comment]
1.5.1正常

**Comment by aa65535** [comment]
新添加了 resolveip 的依赖，所以需要先 `opkg install resolveip`

**Comment by xaoxong** [comment]
@lwd2136  请问怎么解决的？
