### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by xingezhang** [shadowsocks/openwrt-shadowsocks#340]
CC       libshadowsocks_libev_la-udprelay.lo
udprelay.c:50:18: fatal error: udns.h: No such file or directory
compilation terminated.
Makefile:878: recipe for target 'libshadowsocks_libev_la-udprelay.lo' failed
make[5]: *** [libshadowsocks_libev_la-udprelay.lo] Error 1

最新版编译时出现error，该怎么解决？

**Comment by xingezhang** [comment]
看起来好像是编译udprelay.c时找不到udns.h，可是libudns已经通过patch了，不知道该如何破？

**Comment by aa65535** [comment]
修改过 Makefile ?

**Comment by xingezhang** [comment]
是，用了shadowsocks-libev最新的commit

**Comment by aa65535** [comment]
那么你需要同时修改 patch, 否则 patch 会应用失败。

**Comment by xingezhang** [comment]
patch也修改了，之前没问题，这次不知道哪里出错了

**Comment by aa65535** [comment]
使用 V=s 选项查看 patch 应用信息。

**Comment by xingezhang** [comment]
好的，我试试看再来回报

**Comment by aa65535** [comment]
try 76c6043

**Comment by xingezhang** [comment]
@aa65535 昨天没时间试，今天回来就看到更新了。非常感谢！新版编译已经成功了。
