### ISSUE TITLE
3.0.3编译发生问题

### ISSUE THREAD

**Issue by muronghan** [shadowsocks/openwrt-shadowsocks#345]
如题，具体表现在，最新的LEDE，如果单独编译，则没有问题；如果在make menuconfig时选了shadowsocks-libev，编译中断

**Comment by muronghan** [comment]
嗯，我手工添加了libudns（好像最新的LEDE不含？），编译就成功了。

**Comment by rule2c** [comment]
如何手工添加啊？ @muronghan

**Comment by lixingcong** [comment]
@rule2c 

https://github.com/shadowsocks/openwrt-shadowsocks/issues/343#issuecomment-281995578

**Comment by tianlichunhong** [comment]
对呀！如何手动添加libudns？还请大侠详细指导

**Comment by muronghan** [comment]
@rule2c @tianlichunhong 看https://github.com/shadowsocks/openwrt-feeds/tree/master/base，将libudns目录和下面的文件拷贝到编译环境的..../source/package/libs下面，编译时因为是关联包，所以选ss即可，自动会选上的。
