### ISSUE TITLE
Ubuntu16.04 has been install libudns-dev  but type configure: error: Couldn't find libudns

### ISSUE THREAD

**Issue by hehewocao** [shadowsocks/openwrt-shadowsocks#346]
Hello friends !
I'm building openwrt-shadowsocks 3.03  source got error .
linux version : Ubuntu 16.04
built source: LEDE （码源版本在这个 issue提交的三天前git的码源，请原谅我的git应用水平渣渣）

Here ia my openwrt-shadowsocks makefile
```
include $(TOPDIR)/rules.mk

PKG_NAME:=shadowsocks-libev
PKG_VERSION:=3.0.3
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/shadowsocks/shadowsocks-libev.git
PKG_SOURCE_SUBDIR:=$(PKG_NAME)-$(PKG_VERSION)-$(PKG_RELEASE)
PKG_SOURCE_VERSION:=e9c1116f0f9e5a1876df32a9cad83d9b65475339

```
when it trip : Try installing libudns-dev or udns-devel.
I run  `sudo apt-get install libudns-dev`
I found udns.h file is in "/usr/include/udns.h"
But Irun "make V=99"  it type 
```
checking udns.h usability... no
checking udns.h presence... no
checking for udns.h... no
```
what can i do foe it ?

大意就是在编译shadowsocks-libev 的e9c1116f0f9e5a1876df32a9cad83d9b65475339这个版本的码源时报错，我已经安装了 libudns-dev 但是提示找不到udns.h，可是udns.h文件已经存在于/usr/include/udns.h

请问大神，我这种情况下应该怎么办？

请原谅我的英语水平。

**Comment by aa65535** [comment]
https://github.com/shadowsocks/openwrt-shadowsocks#编译
```
git clone https://github.com/shadowsocks/openwrt-feeds.git package/feeds
```
