### ISSUE TITLE
将 openwrt-feeds 中的 pcre 源换一下

### ISSUE THREAD

**Issue by t123yh** [shadowsocks/openwrt-shadowsocks#347]
ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/ 这个链接的服务器实在是很慢，根本无法下载，导致编译失败。
换成 https 更加安全、快速：https://ftp.pcre.org/pub/pcre/pcre-8.40.zip

**Comment by t123yh** [comment]
经检查，是我的路由器设置了仅代理 20 - 1023 端口，导致 ftp 尝试使用高位端口传输失败。但还是建议切换到 https，毕竟保证安全。

**Comment by aa65535** [comment]
fix via https://github.com/shadowsocks/openwrt-feeds/commit/29018347c13eaca1591d609f46c4f6857c62f2cf
