### ISSUE TITLE
3.0.3 build failed - configure: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.

### ISSUE THREAD

**Issue by tedaz** [shadowsocks/openwrt-shadowsocks#348]
What version of shadowsocks-libev are you using?
Shadowsocks-libev 3.0.3 OpenWRT version.

What operating system are you using?
Ubuntu 14.04

What did you do?
Build shadowsocks-libev.

What did you expect to see?

What did you see instead?
configure: error: Couldn't find libudns. Try installing libudns-dev or udns-devel.
make[2]: *** [/lede/build_dir/target-x86_64_musl/shadowsocks-libev//shadowsocks-libev-3.0.3-1/.configured_378b7d77286ceb1b05fea273476f3a6c] Error 1

What is your config in detail (with all sensitive info masked)?
Already installed libudns-dev, but Ubuntu does not have the package udns-devel.
With the same Ubuntu system and same software packages, build 3.0.1 successfully.
It seems that the 3.0.3 have some issues.

**Comment by lixingcong** [comment]
https://github.com/shadowsocks/openwrt-shadowsocks/issues/346#issuecomment-282626221
