### ISSUE TITLE
编译所需的软件包均安装完毕但是还是编译失败

### ISSUE THREAD

**Issue by jetray** [shadowsocks/openwrt-shadowsocks#351]
系统为全新安装的ubuntu16.10，根据官网指导安装完编译软件包后，又在官网下载了对应的SDK，之后的操作都是你给出的命令，结果在make menuconfig过程中出错了，下面是输出结果：
make -s -C scripts/config all CC=cc: build failed. Please re-run make with -j1 V=s to see what's going on
/home/jetray/OpenWrtSDK/include/toplevel.mk:89: recipe for target 'scripts/config/mconf' failed
make: *** [scripts/config/mconf] Error 1

**Comment by aa65535** [comment]
#337
https://forum.openwrt.org/viewtopic.php?id=64798
