### ISSUE TITLE
lede源码下编译make menuconfig后没有aa65535大神的shadowsocks-libev选项

### ISSUE THREAD

**Issue by xiasonming** [shadowsocks/openwrt-shadowsocks#353]
以前在openwrt15.05源码下编译没有这问题，但是lede源码的feeds源自带了shadowsocks-libev，make menuconfig后没有aa65535大神的shadowsocks-libev选项。我想可能是feeds源的shadowsocks-libev和aa65535大神的shadowsocks-libev有冲突，要怎么样解决这问题呢？烦请大神解帮忙解惑，谢谢！

**Comment by aa65535** [comment]
去掉 packages feeds 里的 shadowsocks-libev，然后用这个替换。

**Comment by xiasonming** [comment]
谢谢大神的热心回复，安装你的办法确实可以解决问题，只是这样有点麻烦，要是大神能在以后版本中做一些对应的修改就更完美了。
