### ISSUE TITLE
Failed to access internet when check "Ignore resolve file" at "DHCP and DNS"

### ISSUE THREAD

**Issue by yukeiyang** [shadowsocks/openwrt-shadowsocks#355]
**_Great Job for openwrt
Thanks for your work._**

**Router:** 
Xiaomi Mini

**Openwrt:** 
15.05

**Shadowsocks-libev:**
The Newest version compiled. 

**LUCI:**
The Newest version, All for Shadowsocks-libev, ChinaDNS, DNSForwarder

**Simple-obfs:** 
v0.0.3

**Services:**
ShadowSocks - Access Control - Bypassed IP List - Choose "ChinaDNS-CHNROUTE"

**Network：**
DHCP and DNS - DNS forwardings - Filled with "0.0.0.0#5353"

**After check "Ignore resolve file" for /tmp/resolv.conf.auto, The router will failed to access the internet.**

If leave it by default, ss runs seems ok, just not stable enough, especially in mobile. So, Do i need to check this option? or, just leave it by default to resolv.conf.auto?

Can u give me some suggestions?

**Comment by aa65535** [comment]
```sh
echo 'search lan' >/etc/resolv.conf
echo 'nameserver 127.0.0.1' >>/etc/resolv.conf
```

**Comment by yukeiyang** [comment]
**@aa65535 Thanks for your help. In my case, Success after these steps below:**

**1. ShadowSocks - General Settings - Port Forward**
       - Local Port - 5300
       - Destination - 8.8.4.4:53

**2. ShadowSocks - Access Control - Zone LAN **
       - Proxy Type - Nomal
       - Self Proxy - Global
 
**3. DNS-Forwarder**     
       - Listen Port - 5301 

**4. ChinaDNS**
       - Upstream Servers - 114.114.114.114,127.0.0.1:5301

**5. DHCP and DNS - General Settings** 
       - DNS forwardings - 127.0.0.1#5353
       - Resolv and Hosts Files - Ignore resolve file  (check it)
                                              - Ignore Hosts files   (check it)
