### ISSUE TITLE
3.0.3版本安装提示缺少依赖，2.6.2版本安装iptables-mod-tproxy提示找不到nf_tproxy_core

### ISSUE THREAD

**Issue by lifong2002** [shadowsocks/openwrt-shadowsocks#358]
3.0.3版本安装提示：
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev:
 * 	libudns * 	libmbedtls * 
 * opkg_install_cmd: Cannot install package shadowsocks-libev.
求教这2个依赖怎么加。

2.6.2版本安装iptables-mod-tproxy提示：
failed to find a module named nf_tproxy_core
这个问题我看15年就有人在问了，试过安装openwrt 15.05版本（当前15.05.1），还是这个问题。
kmod-ipt-tproxy里的nf_tproxy_core不装会影响到什么啊？

挂上代理后系统会时不时DNS解析失效几分钟，不知道是不是这个造成的。
感谢回答。

**Comment by aa65535** [comment]
https://dl.bintray.com/aa65535/opkg/shadowsocks-libev/3.0.3/ 里面可以找到 libudns 和 libmbedtls 的 ipk，手动安装即可。

至于 nf_tproxy_core 属于固件问题，但我没有遇到过。
