### ISSUE TITLE
无法启动shadowsocks

### ISSUE THREAD

**Issue by cnmchinagfw** [shadowsocks/openwrt-shadowsocks#359]
看到更新了3.0.4，发现可以支持双核，就升级了，看到下载目录里有新版的libmbedtls_2.4.2，也一并更新了，升级后无法启动服务，显示以下两行字：
Error relocating /usr/bin/ss-redir: crypto_aead_xchacha20poly1305_ietf_decrypt symbol not found
Collected errors:
 * resolve_conffiles: Existing conffile /etc/config/shadowsocks is different from the conffile in the new package. The new conffile will be placed at /etc/config/shadowsocks-opkg.
请问如何解决？谢谢。所有lib都是最新版。

**Comment by aa65535** [comment]
https://github.com/shadowsocks/shadowsocks-libev/issues/1364

**Comment by cnmchinagfw** [comment]
已解决，libsodium版本低了，谢谢。
