### ISSUE TITLE
找不到libudns。。。LEDE依赖问题

### ISSUE THREAD

**Issue by lunarjoll** [shadowsocks/openwrt-shadowsocks#366]
虽然看到了这块只发编译相关的问题。。所以先道个歉。。。
LEDE哪里有libudns吗？？
root@LEDE:~# opkg install shadowsocks-libev_3.0.5-1_mips_24kc.ipk
Installing shadowsocks-libev (3.0.5-1) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev:
 *      libudns *
 * opkg_install_cmd: Cannot install package shadowsocks-libev.
root@LEDE:~# opkg install libudns
Unknown package 'libudns'.
Collected errors:
 * opkg_install_cmd: Cannot install package libudns.

**Comment by lixingcong** [comment]
https://dl.bintray.com/aa65535/opkg/shadowsocks-libev/3.0.5/LEDE/mips_24kc/

这里有Libudns.ipk
