### ISSUE TITLE
dd-wrt support?

### ISSUE THREAD

**Issue by rogers0** [shadowsocks/openwrt-shadowsocks#370]
I know this project is for openwrt support, but how about dd-wrt?
Is it simply applicable to dd-wrt?

dd-wrt is also quite active, with frequent updates:
 - http://download1.dd-wrt.com/dd-wrtv2/downloads/betas/2017/
so maybe you can consider to support it, in near or not-far-away future.
thanks!

**Comment by aa65535** [comment]
I'm not using DD-WRT, you can try this: https://www.dd-wrt.com/wiki/index.php/Ipkg .
