### ISSUE TITLE
适用lede17.2编译后，界面上提示shadowsocks-libev binary file not found.

### ISSUE THREAD

**Issue by zxl78585** [shadowsocks/openwrt-shadowsocks#378]
在基本设置里面显示：shadowsocks-libev binary file not found.
在服务器管理页面，是可以添加和编辑服务器的

**Comment by aa65535** [comment]
说明 `ss-redir ss-local ss-tunnel` 都不存在，检查是否安装了 shadowsocks-libev 这个软件包。
