### ISSUE TITLE
2.0.7不能监听ipv6地址

### ISSUE THREAD

**Issue by sadoneli** [shadowsocks/openwrt-shadowsocks#38]
从2.0.3升上来的，发现2.0.7的ss-local不能监听ipv6地址了，ss-redir尚未测试，已经退回2.0.3，请修复并告知稳定版本。谢谢～

**Comment by aa65535** [comment]
先检查配置，配置没有问题的话请至 [shadowsocks/shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev/issues) 提 issue.
