### ISSUE TITLE
如何代理全部udp

### ISSUE THREAD

**Issue by evollost** [shadowsocks/openwrt-shadowsocks#40]
假设vps端配置正常。
在路由openwrt安装spec版，能否转发局域网中的udp流量（一些特殊的软件还是会走udp）；
若不行，sslocal版+redsocks2可否满足要求？

**Comment by aa65535** [comment]
shadowsocks 无法满足需求，可以尝试使用 ShadowVPN 。

**Comment by evollost** [comment]
不能通过spec版的tunnel转发udp流量么，智能或全局代理udp都行。
之前极路由ss插件没被下架的时候，那一款是可以转发udp的，不知道搭配的什么软件

**Comment by aa65535** [comment]
@evollost 
udprelay 只支持单个的 IP:PORT, 随机的 IP:PORT不论是 ss-tunnel 还是 redsocks 都是不支持的。

**Comment by evollost** [comment]
@aa65535 嗯,下午都试了下也发现了.
想转用shadowvpn,但是所在网络udp都是封锁的,尝试过shadowvpn.conf地址填127.0.0.1,
通过ss-tunnel转发vps_addr:svpn_port,
ss-tunnel不断刷新:
[udp] server receive a packet
[udp] cache hit: vps_addr:svpn_port <-> 127.0.0.1:46007
服务端无输出,估计是udp包类型不对...

**Comment by clowwindy** [comment]
ss-tunnel 也是通过 UDP
