### ISSUE TITLE
AP模式openwrt不能启动ss-rules

### ISSUE THREAD

**Issue by sinowood** [shadowsocks/openwrt-shadowsocks#42]
我的路由器是电信的设备，openwrt路由器是Wifi AP模式。想实现wifi连接的客户端能使用shadowsocks+chinadns自动翻墙，但是出现以下错误，请问有无解决方法? iptables是启动了的，chinadns也能正常启动。
/etc/init.d/shadowsocks start
ss-rules[2799]: Can't redirect, please check the iptables.
感谢

**Comment by aa65535** [comment]
有这个错误说明路由的 iptables 不支持 REDIRECT ，且没有LAN IP，于是 DNAT 也不能使用。
即使不报错，使用 Wifi AP模式也是无法代理的，因为路由自身不会有IP，
可以参考 #8 的回复或者参考 https://www.v2ex.com/t/145758#r_1544923 改一下网络结构。

**Comment by sinowood** [comment]
谢谢，我按照你的思路再研究一下！

**Comment by wongsyrone** [comment]
@sinowood 尝试编译进iptables-nat-extra再试试REDIRECT
