### ISSUE TITLE
openwrt重启后,shadowsocks-spec无法运行,手动启动报错

### ISSUE THREAD

**Issue by evollost** [shadowsocks/openwrt-shadowsocks#43]
/etc/init.d/shadowsocks start:
ipset v6.20.1: Error in line 20: Syntax error: '2147483647' is out of range 0-255
iptables-restore v1.4.21: invalid mask `2147483647' specified
Error occurred at line: 21
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
彻底重装shadowsocks-libev-spec后正常

**Comment by aa65535** [comment]
`/etc/shadowsocks/ignore.list` 中有不标准 IP 行。
