### ISSUE TITLE
shadowsocks-libev-spec 无法开机自启动

### ISSUE THREAD

**Issue by isbaseby** [shadowsocks/openwrt-shadowsocks#44]
启动项里已经显示启用  但是每次重启后shadowsocks都是未运行  需要手动启动

**Comment by aa65535** [comment]
一般是因为 server 填写的是域名，检查一下系统日志里的错误信息。

**Comment by isbaseby** [comment]
感谢，折腾了半天鬼使神差的好了，但是启动项里shadowsocks自动变为禁用了
