### ISSUE TITLE
在openwrt上如何确定shadowsock已经连接服务器

### ISSUE THREAD

**Issue by fantastxu** [shadowsocks/openwrt-shadowsocks#45]
我用的是最新的shadowsocks-libev-polarssl_2.1.2-2_ar71xx.ipk 安装在openwrt上。
想请教几个问题：
1：在路由器上，成功运行 ss-redir，用top也可以看见进程，但是如何判断shadowsocks已经成功连上服务器？ 我有尝试过吧shadowsocks.json里面的服务器ip地址随便改一个，发现ss-redir照样可以运行，也不会有任何报错，进程也在。我现在怀疑shadowsocks没连上服务器
2：spec版本相对来说有哪些优化？还是说只是去掉了local加上了rules
3: 在现有的已经安装了polarssl的路由上，如何卸载原来的shadowsocks安装spec版本呢？

感谢！

**Comment by myliyifei** [comment]
SS没有握手过程，只能用其他网络命令测试连通性。

2015-02-08 10:07 GMT+08:00 Rin Satsuki <notifications@github.com>:
