### ISSUE TITLE
resolveip安装失败

### ISSUE THREAD

**Issue by draculalee** [shadowsocks/openwrt-shadowsocks#48]
我在安装时提示需要resolveip，搜索了下输入opkg install resolveip提示unknow package。然后我在网上搜到一个resolveip_2_ar71xx.ipk进行安装，但是系统仍然提示错误
Configuring resolveip.
//usr/lib/opkg/info/resolveip.postinst: line 4: default_postinst: not found
Collected errors:
 * pkg_run_script: package "resolveip" postinst script returned status 127.
 * opkg_configure: resolveip.postinst returned 127.
搜了半天也不知道该如何处理，能否麻烦帮忙看一下，谢谢。

**Comment by aa65535** [comment]
更新你的 base-files，或者根据 aa65535/openwrt-dnsmasq#3 解决。
