### ISSUE TITLE
shadowsocks-libev-spec经常出现无法连网

### ISSUE THREAD

**Issue by isbaseby** [shadowsocks/openwrt-shadowsocks#50]
shadowsocks-libev-spec	2.1.4-1
OpenWrt Barrier Breaker 14.07 / LuCI Trunk (0.12+svn-r10530)

启动了透明代理正常使用一段时间后就会出现无法联网的状况，进程是存在的，即使重启之后依然无法联网。

**Comment by unitone** [comment]
不知是否开启了QOS，我的开启QOS后，流量过大时会导致shadowsocks无法联网

**Comment by isbaseby** [comment]
没有开启，正常流量
2015年3月29日 上午2:22于 "unitone" <notifications@github.com>写道：

**Comment by unitone** [comment]
VPS 上的 crontab 监控改成1分钟一次看看。
