### ISSUE TITLE
[Feature Request] ipset域名白名单功能

### ISSUE THREAD

**Issue by zhou13** [shadowsocks/openwrt-shadowsocks#53]
有些时候，使用chnroute重定向所有国外流量并不是我所期望的。比如说在国内高校查阅学术图书馆的文献，对方会根据你的IP来判定你是不是订阅用户。这时候如果走代理那么就无法访问付费墙后面的内容。

最简单的解决方法是把常用文献网站的IP添加到chnroute.txt。但这样不太稳定，毕竟某些网站IP变化太快。

另一个方法是在目前的openwrt-shadowsocks的脚本提供一个ipset白名单。然后我们可以在dnsmasq-full中将所需的域名ipset到这个白名单中来解决问题。

**Comment by wongsyrone** [comment]
不建议引入，该功能应由用户自行配置，况且网上已经有了大量的教程

**Comment by zhou13** [comment]
1. 用户自行配置会覆盖目前/etc/init.d/shadowsocks设置的iptable项

2. 你是否真的看懂了我的说明？常用的教程都是配置ipset黑名单，在ipset里面的ip走ss。这里说的是让ipset里的不走代理。

**Comment by aa65535** [comment]
如果你需要在 dnsmasq-full 中指定不走 shadowsocks 的 ipset 的话，可以使用 `ss_spec_wan_ac` 这个 ipset.
```
ipset=/example.com/ss_spec_wan_ac
```

**Comment by yech1990** [comment]
急需这样的功能，感觉回复根本就不知道楼主的需求

**Comment by zhou13** [comment]
`ss_spec_wan_ac`可以解决问题。
