### ISSUE TITLE
使用chacha20验证后无法UDP转发？

### ISSUE THREAD

**Issue by wzhy90** [shadowsocks/openwrt-shadowsocks#56]
服务器端使用chacha20验证后客户端启用UDP转发就无法解析域名了。
是libsodium的问题还是shadowsocks的问题？
上次写的issues应该也是这个问题，因为之前我没发现手机开的时候没打开UDP转发。

**Comment by wongsyrone** [comment]
这个你应该汇报到上游shadowsocks libev吧
