### ISSUE TITLE
流量一高就回到代理前状态的解决

### ISSUE THREAD

**Issue by Sakura-Winkey** [shadowsocks/openwrt-shadowsocks#58]
RT，能不能做一个类似守护进程的脚本，监视这个代理，代理一断马上重启
（PS：无状态的SS做起来难度高么？

**Comment by wongsyrone** [comment]
这种情况一般是cpu处理速度跟不上吧，可以使用cpulimit这样的工具限制ss，或者上个好路由吧，我的能跑满带宽

**Comment by Sakura-Winkey** [comment]
后来检查不是ss程式本身的问题（一开始我也怀疑是cpu跟不上），是防火墙的prerouting链问题，但还是谢谢了
（PS：我在openwrt执行『wget -qO- http://ipecho.net/plain』得知

**Comment by wongsyrone** [comment]
@Sakura-Winkey  你用的是aa65535的spec版本吗，如果是就爱莫能助了

**Comment by Sakura-Winkey** [comment]
是啊，不然我就不会在这里吵吵闹闹了（呵呵

**Comment by aa65535** [comment]
@Sakura-Winkey 
现在是将代理应用到 `zone_lan_prerouting` 链上的，有什么问题吗？
「回到代理前状态」具体是指？

**Comment by Sakura-Winkey** [comment]
是的，后来经过测试问题确实是在zone_lan_prerouting上，详细的话另一个issue有提及，我尝试提供个idea解决
