### ISSUE TITLE
是否可以增加一个选项，默认不启动ss-rules?

### ISSUE THREAD

**Issue by lifetyper** [shadowsocks/openwrt-shadowsocks#60]
例如我要用dnsmasq的IPSET功能来自定义哪些IP走SS，而不是用chnroute这种大范围代理的方式，所以我默认其实不需要ss-rule提供代理规则。
这个是可以通过修改启动文件来实现，但如果做成一个config中可控的选项，会方便很多。谢谢！

**Comment by aa65535** [comment]
如果用不到 ss-rule 的话，不使用 spec 版本就行了。

**Comment by lifetyper** [comment]
嗯，我后来才注意到这个，确实也改用非spec版本了。
