### ISSUE TITLE
请问石像鬼怎么安装ss

### ISSUE THREAD

**Issue by lixingcong** [shadowsocks/openwrt-shadowsocks#61]
路由器 TP 841n V5 ，主控是71xx系列的。
石像鬼1.5.10
用的是openwrt AA 12.09 final的源
ssh执行 opkg install libpolarssl成功
拷贝shadowsocks-libev-spec-polarssl_2.1.4-1_ar71xx.ipk到/tmp
执行opkg install 提示
ERROR: No package named shadowsocks-libev-spec-polarssl_2.1.4-1_ar71xx found, try updating your package lists
请问如何安装呢？是不是要编译啊

**Comment by aa65535** [comment]
确认输入的 opkg install 命令路径正确。
