### ISSUE TITLE
shadowsocks spec 無法啓動

### ISSUE THREAD

**Issue by chor** [shadowsocks/openwrt-shadowsocks#63]
我的shadowsocks 突然無法啓動，luci上提示未運行，端口也沒開。有沒有方法看日誌

**Comment by chor** [comment]
iptables 報這個
iptables-restore v1.4.21: Couldn't load target `SS_SPEC_WAN_FW':No such file or directory

**Comment by chor** [comment]
iptables-restore v1.4.21: Couldn't load target `SS_SPEC_WAN_FW':No such file or directory

**Comment by aa65535** [comment]
可以查看 系统日志，搜索其中的 `ss-rules`

**Comment by chor** [comment]
重新刷过固件就好了
