### ISSUE TITLE
Help to test TPROXY

### ISSUE THREAD

**Issue by madeye** [shadowsocks/openwrt-shadowsocks#64]
I'm working on TPROXY support of shadowsocks-libev, which will help to forward UDP traffic on OpenWRT router: https://github.com/shadowsocks/shadowsocks-libev/tree/tproxy

Could you help to test it on OpenWRT? 

More details:
https://github.com/lparam/xsocks
https://www.kernel.org/doc/Documentation/networking/tproxy.txt

**Comment by aa65535** [comment]
Good job. I'll test it.

**Comment by aa65535** [comment]
recipe for target 'ss_redir-udprelay.o' failed
```
udprelay.c: In function 'get_dstaddr':
udprelay.c:148:57: error: 'IP_RECVORIGDSTADDR' undeclared (first use in this function)
         if (cmsg->cmsg_level == SOL_IP && cmsg->cmsg_type == IP_RECVORIGDSTADDR) {
                                                         ^
udprelay.c:148:57: note: each undeclared identifier is reported only once for each function it appears in
udprelay.c: In function 'remote_recv_cb':
udprelay.c:650:33: error: 'IP_TRANSPARENT' undeclared (first use in this function)
     if (setsockopt(src_sock, SOL_IP, IP_TRANSPARENT, &opt, sizeof(opt))) {
                                 ^
```

may be required:
```c
#ifndef IP_TRANSPARENT
#define IP_TRANSPARENT       19
#endif

#ifndef IP_RECVORIGDSTADDR
#define IP_RECVORIGDSTADDR   20
#endif
```

**Comment by madeye** [comment]
Tests passed on OpenWRT 14.07. Merged to the master branch.

**Comment by shifengjiang** [comment]
have you tested on Linux router? I tried to setup on my debian 8.2 but found failed. On my another old Debian 7.x box with shadowsocks-libev 2.0.1 it works. B.T.W. I noticed the ss-dir listening address changed from 0.0.0.0 to 127.0.0.1. Does it matter?
