### ISSUE TITLE
ss-rules用到了iptables的--to-port命令，希望说明里能说明一下需要安装 iptables-mod-nat-extra

### ISSUE THREAD

**Issue by lersh** [shadowsocks/openwrt-shadowsocks#66]
ss-rules用到了iptables的--to-port命令，希望说明里能说明一下需要安装 iptables-mod-nat-extra。不然启动时也不会有任何错误提示，很有可能造成透明代理不生效

**Comment by aa65535** [comment]
这个跟固件版本有关，` iptables-mod-nat-extra` 包并不是必需的。

**Comment by lersh** [comment]
最好说明下可能需要安装 iptables-mod-nat-extra，因为重复装了不会出错，但少了就不能运行
