### ISSUE TITLE
请问下2.2.0非spec版本的tcp+udp如何设置？

### ISSUE THREAD

**Issue by xqdoo00o** [shadowsocks/openwrt-shadowsocks#67]
我知道spec版本的在luci里面配置，非spec版本的我改成默认ss-redir和ss-tunnel，是默认启动tcp+udp的吗？还是要自己改？谢谢。

**Comment by lersh** [comment]
透明代理需要配iptables规则和dnsmasq的解析转发，可以参考ss-tunnel脚本

**Comment by aa65535** [comment]
加 `-u` 参数打开 udprelay

https://github.com/shadowsocks/shadowsocks-libev#advanced-usage
