### ISSUE TITLE
tcp+udp模式下，在路由器命令行发出的udp请求不会被ss转发?

### ISSUE THREAD

**Issue by niclau** [shadowsocks/openwrt-shadowsocks#68]
openwrt终端下dig twitter
root@OpenWrt:~# dig +short twitter.com @208.67.222.222
74.125.39.113
root@OpenWrt:~# dig +short twitter.com @208.67.222.222
74.125.155.102
root@OpenWrt:~# dig +short twitter.com @208.67.222.222
243.185.187.39

windows下则正确获取ip
C:\Users\user>nslookup twitter.com 208.67.222.222
服务器:  resolver1.opendns.com
Address:  208.67.222.222

非权威应答:
名称:    twitter.com
Addresses:  199.59.148.82
          199.59.148.10
          199.59.150.7
          199.59.149.230

路由器mw4530r openwrt官方14.07, r42625
shadowsocks版本
root@OpenWrt:~# opkg list-installed |grep shadowsocks
luci-app-shadowsocks-spec - 1.3.2-1
shadowsocks-libev-spec-polarssl - 2.2.0-1

**Comment by aa65535** [comment]
是不会转发自身的UDP，
自身的DNS查询使用 ss-tunnel

**Comment by niclau** [comment]
@aa65535 明白，谢谢。
