### ISSUE TITLE
请问非spec版本udp的iptables规则怎么设置？

### ISSUE THREAD

**Issue by xqdoo00o** [shadowsocks/openwrt-shadowsocks#69]
目前是dnsmasq+ipset的方案，https://cokebar.info/archives/962
有三条规则：ipset -N gfwlist iphash
iptables -t nat -A PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080
iptables -t nat -A OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1080
貌似只有tcp的，udp的iptables规则要怎么写呢？

**Comment by aa65535** [comment]
Duplicate with #67
