### ISSUE TITLE
2.2.0版本安装出错 依赖问题

### ISSUE THREAD

**Issue by evollost** [shadowsocks/openwrt-shadowsocks#70]
Multiple packages (kmod-ipt-conntrack and kmod-ipt-conntrack) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (kmod-ipv6 and kmod-ipv6) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (kmod-ip6tables and kmod-ip6tables) providing same name marked HOLD or PREFER. Using latest.
Multiple packages (kmod-ipt-core and kmod-ipt-core) providing same name marked HOLD or PREFER. Using latest.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for shadowsocks-libev-spec:
 *      kernel (= 3.10.49-1-194d0e9ee3ca8df976c737e78e8b2194) *
 * opkg_install_cmd: Cannot install package shadowsocks-libev-spec.

openwrt 版本 :3.10.64
之前安装,使用2.1版本均正常

**Comment by aa65535** [comment]
v2.2.0 添加了新的依赖，此错误是因为内核版本不匹配造成的。
如果不是对 udp转发 特别需要，建议继续使用 v2.1.4
当然，你也可以刷一个新的固件（但不建议使用 trunk）
