### ISSUE TITLE
无法使用chacha20的加密方式？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/openwrt-shadowsocks#72]
小米路由器mini，刷了openwrt，ramips架构的cpu。

版本：2.2.0

rc4-md5和aes-256-cfb的加密方式都行，但是我换成chacha20就连接不上了。服务端libev版，我用手机版和windows版的客户端试过是支持chacha20的。只是openwrt版不行，求解

**Comment by pexcn** [comment]
补充一点，ssl库是openssl的

**Comment by wongsyrone** [comment]
需要libsodium

**Comment by pexcn** [comment]
@wongsyrone 有openwrt版的？

**Comment by wongsyrone** [comment]
我是自己编译的

**Comment by aa65535** [comment]
经测试，可以正常使用，请检查你的配置。

**Comment by madeye** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-libev/commit/d5765a8bbeaf958053bdc30f73b0004dac57557b

**Comment by wongsyrone** [comment]
@pexcn  chacha20参见官方wiki: https://github.com/shadowsocks/shadowsocks/wiki/Encryption#salsa20-and-chacha20

编译时可以添加libsodium依赖https://github.com/shadowsocks/openwrt-shadowsocks/blob/master/Makefile#L37

**Comment by pexcn** [comment]
好的，谢谢了～
