### ISSUE TITLE
端口持续累积

### ISSUE THREAD

**Issue by Crystommy** [shadowsocks/openwrt-shadowsocks#74]
升级2.2.0之后开启了tcp+udp转发，非常好用，感谢！
但使用一段时间（一般是一天）会挂掉
netstat -nlp 看到上千个udp端口(:::XXXXX)这种（服务端，路由客户端均是如此）
我用的是ipv6连接 请问这种情况正常吗。

**Comment by madeye** [comment]
Use a smaller timeout, like 10s.

**Comment by madeye** [comment]
Or increase your file descriptor limit: http://shadowsocks.org/en/config/advanced.html

**Comment by Crystommy** [comment]
@madeye Thank you! I guess the operation should be performed on both server and client.
The doc writes about tcp, this problem is about udp...So if the doc should be updated..
