### ISSUE TITLE
关于新版本代理模式的疑问

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/openwrt-shadowsocks#75]
一个TCP only，一个TCP+UDP。我开了TCP+UDP，不过好像比TCP only慢。
我的环境是OpenWrt+ChinaDNS+Shadowsocks-spec

请问这两种模式有什么区别？
什么情况下用TCP only或者TCP+UDP呢？

**Comment by pexcn** [comment]
在openwrt用的是解决dns污染的方案5

**Comment by aa65535** [comment]
> 旧版本只支持TCP流量的代理，新版添加了UDP的支持。

如果不了解，就选一个你觉得速度快的方式。
这个跟是方案几没关系的。

**Comment by pexcn** [comment]
嗯，感谢。
