### ISSUE TITLE
ss-redir启动不了

### ISSUE THREAD

**Issue by hdstar2009** [shadowsocks/openwrt-shadowsocks#76]
luci界面应用后只有ss-tunel启动了，ss-redir没有。

root@OpenWrt:~# /etc/init.d/shadowsocks start
ipset v6.20.1: Error in line 1: Cannot open session to kernel.

手工执行后提示上面错误。dnsmasq已经安装的full版，ipset也重装过。网站列举的依赖也都有。

**Comment by hdstar2009** [comment]
好吧，重启后，ss-redir也启动了。但是还有问题，ss并没有连上，我到vps上看不到登陆，vps的ss是正常的，我用极路由上的ss程序是完全正常的（就是说ss账号可以确认没问题）

**Comment by cielpy** [comment]
原问题是因为ipset安装后需要重启，第二个是不是因为DNS的问题，ss-redir开了没效果，配合ChinaDNS试下？

**Comment by aa65535** [comment]
请贴出 uci export shadowsocks 打印的内容。
