### ISSUE TITLE
关于UDP问题

### ISSUE THREAD

**Issue by 100369548** [shadowsocks/openwrt-shadowsocks#80]
最新shadowsocks-libev-spec(2.21)是否支持游戏UDP

**Comment by madeye** [comment]
支持。

**Comment by 100369548** [comment]
为什么我设置好了上youtube不能用QUIC  VPS SS服务已经开启UDP 浏览器也开启QUIC协议了

**Comment by Crystommy** [comment]
清除缓存多刷新几下

**Comment by 100369548** [comment]
还是不行 开启UDP还用其他命令吗 还是LuCI界面设置就可以 代理设置-代理协议-TCP+UDP

**Comment by xcjiang** [comment]
国内网络环境用QUIC没什么好处。
