### ISSUE TITLE
编译/shadowsocks-libev-sepc出错, 编译redsock2, chinadns, shadowvpn都没问题.

### ISSUE THREAD

**Issue by cuteribs** [shadowsocks/openwrt-shadowsocks#83]
OPENWRT源码和SDK都是用的15.05的

checking for readdir... yes
checking for strlcat... yes
checking for strlcpy... yes
configure: error: Invalid kernel source directory /lib/modules/3.16.0-40-generic/source
make[2]: *** [/root/opt/openwrt/build_dir/target-arm_cortex-a7+vfp_uClibc-0.9.33.2_eabi/linux-brcm2708_bcm2709/ipset-6.24/.configured_yyyyyyyy] Error 1
make[2]: Leaving directory `/root/opt/openwrt/package/network/utils/ipset'
make[1]: *** [package/network/utils/ipset/compile] Error 2
make[1]: Leaving directory `/root/opt/openwrt'
make: *** [package/shadowsocks-libev/compile] Error 2

**Comment by aa65535** [comment]
无法重现

http://wiki.openwrt.org/doc/howto/buildroot.exigence
