### ISSUE TITLE
开启SSP

### ISSUE THREAD

**Issue by wongsyrone** [shadowsocks/openwrt-shadowsocks#85]
从 https://github.com/openwrt-mirror/openwrt/commit/8d2b190b89b7895b942346ca88fd07a400407a58 开始，默认开启了常规SSP支持，但是可能是因为使用了`PKG_FIXUP:=autoreconf`的缘故，编译时会出现问题。
解决办法：
在Makefile 中添加 `TARGET_CFLAGS += -fstack-protector`

**Comment by aa65535** [comment]
建议发 pull requests

**Comment by wongsyrone** [comment]
OK
