### ISSUE TITLE
同步#86源代码后，openwrt里shadowsocks无法启动

### ISSUE THREAD

**Issue by mrken2004** [shadowsocks/openwrt-shadowsocks#87]

**Comment by wongsyrone** [comment]
你的OP源码需要基于 https://github.com/openwrt-mirror/openwrt/commit/8d2b190b89b7895b942346ca88fd07a400407a58 之后，如果是老源码编译的固件安装新编译的ss肯定不能启动，因为没开SSP

**Comment by wongsyrone** [comment]
建议重新编译工具链

**Comment by wongsyrone** [comment]
@mrken2004  如果源码是以前的，编译的时候去掉Makefile中的TARGET_CFLAGS += -fstack-protector

**Comment by mrken2004** [comment]
@wongsyrone 你好。我的源代码是每天svn://svn.openwrt.org/openwrt/trunk的，刚才看了一下，提到的代码版本是46020，今天我这里已经更新到46078，是不是应该已经包含SSP了？谢谢！

**Comment by wongsyrone** [comment]
@mrken2004  你可以尝试先 make dirclean 一下，之后重新编译，这样会重新编译带SSP的GCC

**Comment by mrken2004** [comment]
@wongsyrone 好的。非常感谢！这就去试试。虽然我两天前刚刚make dirclean。但是为了保证路由上的关键程序稳定，必须做。

**Comment by wongsyrone** [comment]
@mrken2004  这个PR是我自己测试之后才提交上来的，已经在Qihoo C301上测试过了，如果是新代码编译的话应该是没问题的

**Comment by mrken2004** [comment]
@wongsyrone 非常感谢您的指点。在make dirclean之后重新编译，正常使用。特此回来感谢！
