### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by chenxinxing** [shadowsocks/openwrt-shadowsocks#92]
能否实现多服务器配置？ 如最好的话然后根据不同的延迟可以选择速度最快的连接。

**Comment by aa65535** [comment]
这个需要等 shadowsocks-libev 支持才行了。

**Comment by linuxchang** [comment]
您好，我有一个问题，openwrt 里面启动 shadowsocks的时候 提示 iptables: No chain/target/match by that name.  我按照的是shadowsocks-libev-spec，目前在luci界面里面选择代理方式执行选择 TCP only
