### ISSUE TITLE
Submit openwrt-shadowsocks to the official OpenWRT project

### ISSUE THREAD

**Issue by madeye** [shadowsocks/openwrt-shadowsocks#93]
https://github.com/openwrt/packages

I think we're ready to submit this project to OpenWRT. IMO, `shadowsocks-libev-spec` and corresponding luci project may be the most suitable packages to submit.

**Comment by clowwindy** [comment]
+1

**Comment by aa65535** [comment]
Done, openwrt/packages#1513
