### ISSUE TITLE
openwrt 更新了 shadowsocks-libev 和LUCI后   发现UDP代理不能启动

### ISSUE THREAD

**Issue by linuxchang** [shadowsocks/openwrt-shadowsocks#94]
您好，我有一个问题，openwrt 里面启动 shadowsocks的时候 提示 iptables: No chain/target/match by that name. 我安装的是shadowsocks-libev-spec，目前在luci界面里面选择代理方式之能选择 TCP only

**Comment by linuxchang** [comment]
而且我在路由器里面看了，Iptable里面只有关于TCP的条目，没有关于UDP的

**Comment by linuxchang** [comment]
现在的情况是，如果我在LUCI界面上面选择  TCP only  那么 shadowsocks  启动是没有问题的

**Comment by linuxchang** [comment]
通过观察启动的脚本发现是rules 脚本里面的这句规则
![image](https://cloud.githubusercontent.com/assets/13128788/8470994/cf31bd06-20c5-11e5-8759-46a68078fbe1.png)

**Comment by aa65535** [comment]
有安装 `iptables-mod-tproxy` ？

**Comment by linuxchang** [comment]
我安装了。。 
我用的固件是
![image](https://cloud.githubusercontent.com/assets/13128788/8472383/5d5e9d58-20d3-11e5-85d3-2bd0d119e600.png)
其余的包
![image](https://cloud.githubusercontent.com/assets/13128788/8472388/6db9b2c8-20d3-11e5-8488-eb43a602cf3c.png)
![image](https://cloud.githubusercontent.com/assets/13128788/8472396/82e186ee-20d3-11e5-87ce-d610ba3a7061.png)
通过产看https://github.com/shadowsocks/openwrt-shadowsocks/blob/master/files/shadowsocks.rule的规则
发现就是TPROXY的规则除了问题
![image](https://cloud.githubusercontent.com/assets/13128788/8472416/bae6d35a-20d3-11e5-8181-e8d2c53d2fac.png)
我在路由器里面也尝试了一下  如果指定 -A   无论是 OUTPUT 还是POSTROUTING  都是一样的错误

**Comment by aa65535** [comment]
安装后重启路由器了吗？

2015年7月2日 16:03于 linuxchang <notifications@github.com>写道：
我安装了。。
我用的固件是
![image](https://cloud.githubusercontent.com/assets/13128788/8472383/5d5e9d58-20d3-11e5-85d3-2bd0d119e600.png)
其余的包
![image](https://cloud.githubusercontent.com/assets/13128788/8472388/6db9b2c8-20d3-11e5-8488-eb43a602cf3c.png)
![image](https://cloud.githubusercontent.com/assets/13128788/8472396/82e186ee-20d3-11e5-87ce-d610ba3a7061.png)
通过产看https://github.com/shadowsocks/openwrt-shadowsocks/blob/master/files/shadowsocks.rule的规则
发现就是TPROXY的规则除了问题
![image](https://cloud.githubusercontent.com/assets/13128788/8472416/bae6d35a-20d3-11e5-8181-e8d2c53d2fac.png)
我在路由器里面也尝试了一下  如果指定 -A   无论是 OUTPUT 还是POSTROUTING  都是一样的错误

---

**Comment by linuxchang** [comment]
我重启了很多次了！  我现在怀疑是iptables 的这个模块有问题，希望您能帮助我一下

**Comment by linuxchang** [comment]
另外我还有一个问题想问您，我的SS后台用的是这个
https://github.com/mengskysama/shadowsocks/tree/manyuser
用这个是因为他多用户，这个版本说也能支持UDP，但是我不清楚，他说的这个UDP代理很您开发的这个版本有什么区别，网上说只有您开发的libev  才支持UDP代理

**Comment by aa65535** [comment]
跟服务端没关系的，使用 lsmod 命令看看内核模块有没有加载成功。

2015年7月2日 16:14于 linuxchang <notifications@github.com>写道：

**Comment by linuxchang** [comment]
![image](https://cloud.githubusercontent.com/assets/13128788/8472839/28efa3ba-20d7-11e5-93a7-19e287bb8195.png)

然后我把关于TPROXY的2个包重装了，然后重启了  再次执行测试

![image](https://cloud.githubusercontent.com/assets/13128788/8472871/650fb830-20d7-11e5-92ed-0c8a25f0ecab.png)

**Comment by madeye** [comment]
`TPROXY` only works on `PREROUTING` chain.

**Comment by linuxchang** [comment]
现在看来跟指定谁好像没有关系。。。。。

![image](https://cloud.githubusercontent.com/assets/13128788/8472993/7124f864-20d8-11e5-8d18-548f406b7a0a.png)

**Comment by linuxchang** [comment]
就是报错，哎。。。

![image](https://cloud.githubusercontent.com/assets/13128788/8473013/ae6d924e-20d8-11e5-8abd-e08193745790.png)

**Comment by aa65535** [comment]
内核模块名称应该是 xt_TPROXY.
使用 iptables-save -t mangle 看看这个表里有什么规则。

**Comment by linuxchang** [comment]
现在来看应该是模块还是没有。。
![image](https://cloud.githubusercontent.com/assets/13128788/8473088/47f14096-20d9-11e5-989a-277c6a38bf75.png)

mangle规则
![image](https://cloud.githubusercontent.com/assets/13128788/8473096/650ec40a-20d9-11e5-8dbb-a091880a3dfc.png)

启动shadowsocks后的规则
![image](https://cloud.githubusercontent.com/assets/13128788/8473154/d7097b22-20d9-11e5-9d04-cb8ab4443b5e.png)

**Comment by aa65535** [comment]
内核模块没加载成功是没法使用这个功能的。
看看有没有漏掉什么包，内核日志里面看看有没有错误。

**Comment by linuxchang** [comment]
好的！ 因为这个版本的固件自带了很多我不需求的东西，我就都给删了，可能是这个原因，我打算重新刷了。非常感谢您的耐心指导。谢谢
