### ISSUE TITLE
Allow using different IP and ports for TCP and UDP

### ISSUE THREAD

**Issue by clowwindy** [shadowsocks/openwrt-shadowsocks#96]
Maybe it's dangerous to use the same port.

@aa65535 @madeye

**Comment by madeye** [comment]
Two `ss-redir` instances should solve the problem.

**Comment by clowwindy** [comment]
We can add a new configuration entry in LuCI for the UDP settings like this

```
TCP:
- Server:
- Port:
- ...

UDP:
[ ] Use the same as TCP
- Server:
- Port:
- ...
```

**Comment by aa65535** [comment]
This is necessary?

**Comment by clowwindy** [comment]
Some people report that by disabling UDP, they got less chance that their servers get blocked.

**Comment by cokebar** [comment]
UDP is much more unstable. I cannot use TCP+UDP mode on my router. I have a high chance encountering "QUIC protocol error" when using chrome browser with TCP+UDP mode. I have to wait for about 1 min, and the connection recovers. This is definitely GFW's temporary block.
I think UDP connection have a higher chance that the server get blocked.
Mabe using a different port for UDP can protect server's TCP port.

**Comment by clowwindy** [comment]
:+1:
