### ISSUE TITLE
OpenWRT:CHAOS CALMER (15.05-rc2, r45918):failed to find a module named nf_tproxy_core

### ISSUE THREAD

**Issue by hackevin** [shadowsocks/openwrt-shadowsocks#98]
Configuring ip.
Configuring zlib.
Configuring libopenssl.
Configuring resolveip.
Configuring kmod-nfnetlink.
Configuring kmod-ipt-ipset.
Configuring libmnl.
Configuring ipset.
Configuring kmod-ipt-tproxy.
failed to find a module named nf_tproxy_core
Configuring iptables-mod-tproxy.
Configuring shadowsocks-libev-spec.

**Comment by aa65535** [comment]
reboot

**Comment by zlphoenix** [comment]
I also encountered this problem when install shadowsocks-libev package on my 3700 v2. After Reboot router , this package still not found.

**Comment by Steltek** [comment]
Same error message with the released version of Chaos Calmer on ar71xx. Neither iptables-mod-tproxy_1.4.21-1_ar71xx.ipk nor kmod-ipt-tproxy_3.18.20-1_ar71xx.ipk include the nf_tproxy_core file/module. They only include libxt_socket.so and libxt_TPROXY.so. 

Not sure if nf_tproxy_core is actually needed. If it's not, the included /etc/modules.d/ipt-tproxy and postinst-pkg probably shouldn't reference it.

**Comment by ZaXk** [comment]
root@OpenWrt:~# opkg install iptables-mod-tproxy
Installing iptables-mod-tproxy (1.4.21-1) to root...
Downloading http://downloads.openwrt.org/chaos_calmer/15.05/mvebu/generic/packages/base/iptables-mod-tproxy_1.4.21-1_mvebu.ipk.
Installing kmod-ipt-tproxy (3.18.20-1) to root...
Downloading http://downloads.openwrt.org/chaos_calmer/15.05/mvebu/generic/packages/base/kmod-ipt-tproxy_3.18.20-1_mvebu.ipk.
Configuring kmod-ipt-tproxy.
failed to find a module named nf_tproxy_core
xt_socket is already loaded
xt_TPROXY is already loaded
Configuring iptables-mod-tproxy.


Don't know how to fix it!

**Comment by xdrwedc** [comment]
Reboot and install again

Step 1 reboot
Step 2 rm /etc/config/shadowsocks
Step 3 opkg install shadowsocks-libev-spec

no failures anymore

**Comment by jackfengji** [comment]
UDP forwarding is not working without kmod-ipt-tproxy. But when I tried to install kmod-ipt-tproxy, it gives me the error
failed to find a module named nf_tproxy_core

**Comment by yangxuan8282** [comment]
got same issues, fix with:

    opkg update 

    opkg install ip-full

**Comment by oliver661** [comment]
Got same problem when "opkg install kmod-ipt-tproxy"
Reboot, reinstall and everything I found is not working.
And I found this ticket https://bugs.lede-project.org/index.php?do=details&task_id=212 said that 

> nf_tproxy_core was removed during 3.12 development...

So, I think re-flash openwrt by 15.05 version which is not remove nf_tproxy_core or LEDE system which has already fix this issue would work.
